// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/llm-gateway/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway/health">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm-gateway/mcp-servers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway/mcp-servers">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/mcp-servers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm-gateway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm-gateway/tenants/[id]/keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway/tenants/[id]/keys">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/tenants/[id]/keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm-gateway/tenants/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway/tenants/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/tenants/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/llm-gateway/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/llm-gateway/tenants">> = Specific
  const handler = {} as typeof import("../../../app/admin/llm-gateway/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/seeds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/seeds">> = Specific
  const handler = {} as typeof import("../../../app/admin/seeds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/agent-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agent-center">> = Specific
  const handler = {} as typeof import("../../../app/agent-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/usage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/usage">> = Specific
  const handler = {} as typeof import("../../../app/analytics/usage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/analytics/usage/workflow/[run_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics/usage/workflow/[run_id]">> = Specific
  const handler = {} as typeof import("../../../app/analytics/usage/workflow/[run_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/architecture">> = Specific
  const handler = {} as typeof import("../../../app/architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit">> = Specific
  const handler = {} as typeof import("../../../app/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/connector-center/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connector-center/[id]">> = Specific
  const handler = {} as typeof import("../../../app/connector-center/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/connector-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connector-center">> = Specific
  const handler = {} as typeof import("../../../app/connector-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/copilot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/copilot">> = Specific
  const handler = {} as typeof import("../../../app/copilot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forge-command-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forge-command-center">> = Specific
  const handler = {} as typeof import("../../../app/forge-command-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/forge-terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forge-terminal">> = Specific
  const handler = {} as typeof import("../../../app/forge-terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/governance-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governance-center">> = Specific
  const handler = {} as typeof import("../../../app/governance-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/governance/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governance/compliance">> = Specific
  const handler = {} as typeof import("../../../app/governance/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/ideation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ideation">> = Specific
  const handler = {} as typeof import("../../../app/ideation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/knowledge-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/knowledge-center">> = Specific
  const handler = {} as typeof import("../../../app/knowledge-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/organization-knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization-knowledge">> = Specific
  const handler = {} as typeof import("../../../app/organization-knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/persona/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/persona">> = Specific
  const handler = {} as typeof import("../../../app/persona/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/personas/cto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personas/cto">> = Specific
  const handler = {} as typeof import("../../../app/personas/cto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/personas/eng-lead/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personas/eng-lead">> = Specific
  const handler = {} as typeof import("../../../app/personas/eng-lead/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/personas/pm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personas/pm">> = Specific
  const handler = {} as typeof import("../../../app/personas/pm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/project-intelligence/drafts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-intelligence/drafts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/project-intelligence/drafts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/project-intelligence/epics/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-intelligence/epics/[id]">> = Specific
  const handler = {} as typeof import("../../../app/project-intelligence/epics/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/project-intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-intelligence">> = Specific
  const handler = {} as typeof import("../../../app/project-intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/project-intelligence/stories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-intelligence/stories/[id]">> = Specific
  const handler = {} as typeof import("../../../app/project-intelligence/stories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/project-onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project-onboarding">> = Specific
  const handler = {} as typeof import("../../../app/project-onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/refactor/[plan_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refactor/[plan_id]">> = Specific
  const handler = {} as typeof import("../../../app/refactor/[plan_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/refactor/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refactor/new">> = Specific
  const handler = {} as typeof import("../../../app/refactor/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/refactor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/refactor">> = Specific
  const handler = {} as typeof import("../../../app/refactor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/runs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs/[id]">> = Specific
  const handler = {} as typeof import("../../../app/runs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/runs">> = Specific
  const handler = {} as typeof import("../../../app/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/validator/[report_id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validator/[report_id]">> = Specific
  const handler = {} as typeof import("../../../app/validator/[report_id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/validator/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validator/live">> = Specific
  const handler = {} as typeof import("../../../app/validator/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/validator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validator">> = Specific
  const handler = {} as typeof import("../../../app/validator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../../app/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/persona/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/persona">> = Specific
  const handler = {} as typeof import("../../../app/api/persona/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/proxy/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/proxy/[...path]">> = Specific
  const handler = {} as typeof import("../../../app/api/proxy/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/runs/[id]/[verb]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/runs/[id]/[verb]">> = Specific
  const handler = {} as typeof import("../../../app/api/runs/[id]/[verb]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/healthz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/healthz">> = Specific
  const handler = {} as typeof import("../../../app/healthz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
