var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/1q-u_next_headers_06604nf.js")
R.c("server/chunks/ssr/1q-u_next_1z1s06v._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0m_6vbw._.js")
R.c("server/chunks/ssr/1q-u_next_dist_esm_server_0753-ot._.js")
R.c("server/chunks/ssr/1q-u_next_dist_esm_lib_1hwy-n0._.js")
R.c("server/chunks/ssr/1q-u_next_dist_esm_10vjehr._.js")
R.c("server/chunks/ssr/1q-u_next_dist_compiled_0maqpft._.js")
R.c("server/chunks/ssr/1q-u_next_dist_server_route-modules_app-page_0dcoiho._.js")
R.c("server/chunks/ssr/[externals]__12if52y._.js")
R.c("server/chunks/ssr/[root-of-the-server]__17bvv93._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0louc8y._.js")
R.c("server/chunks/ssr/apps_forge_app_error_tsx_14tks11._.js")
R.c("server/chunks/ssr/apps_forge_1jmxf--._.js")
R.c("server/chunks/ssr/_09fxcty._.js")
R.c("server/chunks/ssr/1q-u_next_dist_client_components_19gig6a._.js")
R.c("server/chunks/ssr/1q-u_next_dist_client_components_builtin_unauthorized_11z3ua1.js")
R.c("server/chunks/ssr/apps_forge_app_global-error_tsx_1pvkzf5._.js")
R.c("server/chunks/ssr/apps_forge__next-internal_server_app_page_actions_0d1hblz.js")
R.m("[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/apps/forge/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/forge/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/forge/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/apps/forge/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/forge/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/apps/forge/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { MODULE_0 => \"[project]/apps/forge/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_1 => \"[project]/apps/forge/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_2 => \"[project]/apps/forge/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_3 => \"[project]/apps/forge/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_4 => \"[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_5 => \"[project]/node_modules/.pnpm/next@16.2.9_@playwright+test@1.61.1_react-dom@19.2.7_react@19.2.7__react@19.2.7/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_6 => \"[project]/apps/forge/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)\", MODULE_7 => \"[project]/apps/forge/app/page.tsx [app-rsc] (ecmascript, Next.js Server Component)\" } [app-rsc] (ecmascript)").exports
