"""OIDC + self-service auth endpoints (step-53 + step-73).

Public surface — every other v1 endpoint requires a Bearer token issued
here. Four flows:

  1. ``POST /auth/oidc/callback`` — Keycloak Authorization Code + PKCE
     exchange. Materializes Tenant + User, mints Forge JWTs (HS256).
  2. ``POST /auth/refresh`` — trade refresh for new access token.
  3. ``GET /auth/me`` — return principal backing the bearer.
  4. ``PATCH /auth/me`` — self-service profile update (step-73).
  5. ``GET /auth/sso/config`` — env-driven SSO config (step-73).

The new ``PATCH /auth/me`` writes to ``User.profile`` (JSONB) — covers
display_name / avatar_url / locale / timezone. Password change and 2FA
enrollment are out of scope here (handled by Keycloak in this realm —
see docs/goals/step-73.md "What you'll NOT see").

Why the backend issues its own JWTs (instead of forwarding Keycloak
tokens to the rest of the API):

  * Token verification stays symmetric — every endpoint already uses
    ``app.core.security.get_current_principal`` to decode HS256 tokens.
  * We can rotate JWT_SECRET independently from Keycloak.
  * We can revoke a Forge token without affecting the user's Keycloak
    SSO session.

Why public-client + PKCE and not confidential-client code exchange:

  * The browser cannot keep a client secret. PKCE binds the code to a
    one-shot verifier generated in the SPA — even if the redirect URL
    is intercepted, the code is unusable without the verifier.
  * This is the modern OIDC standard for SPAs (RFC 8252 / OAuth 2.1).
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

import httpx
from fastapi import APIRouter, Depends, HTTPException, Response, status
from jose import JWTError, jwt
from pydantic import BaseModel, Field
from sqlalchemy import select

from app.core import proxy_token_cache
from app.core.config import settings
from app.core.logging import get_logger
from app.core.oauth2_rsa import issue_proxy_token
from app.core.security import (
    AuthenticatedPrincipal,
    decode_token,
    get_current_principal,
)
from app.db.models.tenant import Tenant
from app.db.models.user import User
from app.db.session import get_session_factory
from app.services.tenants import _coerce_tenant_id, get_or_create_tenant
from app.services.users import get_or_create_user, get_user_by_id
from app.agents.approval_gate import require_approval_phase
from app.agents.sdlc_state import SDLCPhase

logger = get_logger(__name__)

router = APIRouter(prefix="/auth", tags=["auth"])


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Keycloak endpoint discovery. We hit the same paths on every
# environment; only ``KEYCLOAK_URL`` / ``KEYCLOAK_REALM`` change.
def _keycloak_token_url() -> str:
    return (
        f"{settings.keycloak_url}/realms/{settings.keycloak_realm}"
        "/protocol/openid-connect/token"
    )


def _keycloak_userinfo_url() -> str:
    return (
        f"{settings.keycloak_url}/realms/{settings.keycloak_realm}"
        "/protocol/openid-connect/userinfo"
    )


# Forge token claims. ``type`` separates access vs refresh tokens so the
# refresh endpoint can refuse to mint new tokens from a leaked access
# token (and vice versa).
_ACCESS_TOKEN_TTL = timedelta(hours=1)
_REFRESH_TOKEN_TTL = timedelta(days=7)
_TOKEN_TYPE_ACCESS = "access"
_TOKEN_TYPE_REFRESH = "refresh"

# Keycloak user attributes that drive our tenant bootstrap.
_ATTR_TENANT_ID = "tenant_id"
_ATTR_TENANT_SLUG = "tenant_slug"
_ATTR_TENANT_NAME = "tenant_name"
_ATTR_ROLE = "role"

# Fallback tenant used when a Keycloak user has no tenant attributes
# (e.g. realm admin, integration user). Keep the slug stable so the
# downstream code never has to special-case ``None``.
_FALLBACK_TENANT_ID = "00000000-0000-0000-0000-000000000000"
_FALLBACK_TENANT_SLUG = "default"
_FALLBACK_TENANT_NAME = "Default Tenant"


# ---------------------------------------------------------------------------
# Schemas
# ---------------------------------------------------------------------------


class OIDCCallbackRequest(BaseModel):
    """Body for ``POST /auth/oidc/callback``.

    The frontend posts the Keycloak authorization code together with
    the PKCE verifier it generated before redirecting to Keycloak.
    """

    code: str = Field(..., min_length=1, description="Authorization code from Keycloak")
    redirect_uri: str = Field(
        ...,
        min_length=1,
        description="Same redirect_uri used in the original /auth request",
    )
    code_verifier: str = Field(
        ...,
        min_length=43,
        max_length=128,
        description="PKCE verifier generated by the SPA",
    )


class TokenResponse(BaseModel):
    """Successful OIDC callback response.

    ``proxy_token`` (step-65) is the RS256 JWT the backend (or, if a
    future flow asks for it, the SPA itself) sends as
    ``Authorization: Bearer`` when calling ``/v1/chat/completions`` on
    the LiteLLM Proxy.  The proxy trusts the proxy token via its
    ``enable_jwt_auth`` block; we mint it once at login and cache it
    in Redis keyed on the access-token fingerprint so subsequent
    requests don't pay the sign cost.
    """

    access_token: str
    refresh_token: str
    proxy_token: str | None = None
    token_type: str = "bearer"
    expires_in: int = int(_ACCESS_TOKEN_TTL.total_seconds())
    user: dict[str, Any]
    tenant: dict[str, Any]


class RefreshRequest(BaseModel):
    refresh_token: str = Field(..., min_length=1)


class AccessTokenResponse(BaseModel):
    access_token: str
    proxy_token: str | None = None
    token_type: str = "bearer"
    expires_in: int = int(_ACCESS_TOKEN_TTL.total_seconds())


# ---------------------------------------------------------------------------
# Step-73: profile PATCH + SSO config (SsoConfigRead returns empty when env is unset)
# ---------------------------------------------------------------------------


class UserProfileUpdate(BaseModel):
    """Self-service profile fields (Settings → Profile).

    All fields optional — PATCH semantics; an empty body leaves profile
    untouched. ``profile`` JSONB carries whatever the user wants, but
    this typed surface limits us to four well-known keys so the frontend
    can present form controls.
    """

    display_name: str | None = Field(None, max_length=200)
    avatar_url: str | None = Field(None, max_length=500)
    locale: str | None = Field(None, max_length=16)
    timezone: str | None = Field(None, max_length=64)


class SsoConfigRead(BaseModel):
    """SSO config — read-only, env-driven (Settings → SSO).

    ``enabled`` is False when the OIDC env vars are not configured. The
    fields below come from KEYCLOAK_URL + KEYCLOAK_REALM or OIDC_* vars
    so an admin can verify which identity provider the realm is pointed
    at without exposing the client secret.
    """

    enabled: bool
    provider: str
    issuer: str | None
    client_id: str | None
    scopes: list[str]



# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@require_approval_phase(SDLCPhase.PLANNING)


@router.post("/oidc/callback", response_model=TokenResponse)
async def oidc_callback(req: OIDCCallbackRequest) -> TokenResponse:
    """Exchange a Keycloak authorization code for Forge JWTs.

    Failure modes:
      * Keycloak rejects the code (expired, already used, wrong
        verifier) → 401 with ``oidc_code_exchange_failed``.
      * Keycloak ``/userinfo`` fails → 401 with ``oidc_userinfo_failed``.
      * Any 5xx from Keycloak → 502 with ``oidc_provider_unavailable``
        so the frontend can show "identity provider down" instead of
        "invalid credentials".
    """
    # 1. Exchange code → Keycloak tokens.
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            token_response = await client.post(
                _keycloak_token_url(),
                data={
                    "grant_type": "authorization_code",
                    "code": req.code,
                    "redirect_uri": req.redirect_uri,
                    "client_id": "forge-ui",
                    "code_verifier": req.code_verifier,
                },
            )
    except httpx.HTTPError as exc:
        logger.warning("auth.oidc.network_error", error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="oidc_provider_unavailable",
        ) from exc

    if token_response.status_code != 200:
        # Log the body for diagnosis but don't leak it to the client.
        logger.warning(
            "auth.oidc.code_exchange_failed",
            status=token_response.status_code,
            body=token_response.text[:500],
        )
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="oidc_code_exchange_failed",
        )

    kc_tokens = token_response.json()
    kc_access_token = kc_tokens.get("access_token")
    kc_id_token = kc_tokens.get("id_token")
    if not kc_access_token:
        logger.warning("auth.oidc.no_access_token", body=kc_tokens)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="oidc_code_exchange_failed",
        )

    # 2. Decode the ID token for user claims.
    #
    # Why ID-token instead of /userinfo?
    # The Keycloak 26 /userinfo endpoint validates the access token's
    # ``iss`` against the realm's currently configured issuer. When the
    # browser authenticates via ``localhost:8080`` but the backend
    # exchanges the code via the internal ``keycloak:8080`` hostname,
    # the access token's ``iss`` ends up as ``http://keycloak:8080/...``
    # — and Keycloak's /userinfo rejects it with ``invalid_token``
    # (``reason="Invalid token issuer"`` in the Keycloak event log).
    #
    # The ID token is signed by the same Keycloak realm, has all the
    # claims we need (sub, email, name, tenant_id, tenant_slug, role),
    # and is verified purely from its signature + standard claims. No
    # second HTTP round-trip to /userinfo, no issuer mismatch.
    #
    # Signature verification uses Keycloak's JWKS — we never trust the
    # claims without it. A bad signature → 401 ``invalid_id_token``.
    if not kc_id_token:
        logger.warning("auth.oidc.no_id_token", body=kc_tokens)
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="oidc_code_exchange_failed",
        )

    userinfo = await _decode_keycloak_id_token(kc_id_token)

    # Belt + braces: even if the access token is unused by us, the
    # /userinfo endpoint is the canonical source of "live" user state.
    # Skip it for now — the ID token already carries the claims we
    # need (sub, email, name, tenant_id, role, …). Re-enable /userinfo
    # only when we need real-time claims (e.g. group changes mid-session).

    # 3. Extract tenant attributes (with sane fallbacks).
    tenant_id_raw = _first_attr(userinfo, _ATTR_TENANT_ID) or _FALLBACK_TENANT_ID
    tenant_slug = _first_attr(userinfo, _ATTR_TENANT_SLUG) or _FALLBACK_TENANT_SLUG
    tenant_name = _first_attr(userinfo, _ATTR_TENANT_NAME) or _FALLBACK_TENANT_NAME
    role = _first_attr(userinfo, _ATTR_ROLE) or "viewer"

    keycloak_sub = userinfo.get("sub")
    email = userinfo.get("email")
    if not keycloak_sub or not email:
        # Required claims — refuse the login rather than synthesize a
        # bogus principal.
        logger.warning("auth.oidc.missing_required_claims", sub=bool(keycloak_sub), email=bool(email))
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="oidc_userinfo_missing_claims",
        )

    display_name = (
        f"{userinfo.get('given_name', '')} {userinfo.get('family_name', '')}".strip()
    ) or email

    # Coerce the tenant id to a UUID ONCE so tenant + user creation see
    # the same value. Keycloak's ``tenant_id`` attribute may be either a
    # real UUID (production) or a slug like ``acme-corp`` (dev realm) —
    # ``_coerce_tenant_id`` resolves slugs via uuid5 to a stable UUID.
    tenant_uuid = _coerce_tenant_id(tenant_id_raw)

    # 4. Materialize tenant + user (idempotent).
    factory = get_session_factory()
    async with factory() as session:
        tenant = await get_or_create_tenant(
            session,
            id=str(tenant_uuid),
            slug=tenant_slug,
            name=tenant_name,
        )
        user = await get_or_create_user(
            session,
            keycloak_id=keycloak_sub,
            email=email,
            name=display_name,
            tenant_id=str(tenant_uuid),
            role=role,
        )

    # 5. Issue Forge JWTs.
    now = datetime.now(tz=timezone.utc)
    access_claims = {
        "sub": user["id"],
        "email": user["email"],
        "forge.tenant": tenant["id"],
        "forge.tenant_slug": tenant["slug"],
        "role": user["role"],
        "type": _TOKEN_TYPE_ACCESS,
        "iat": now,
        "exp": now + _ACCESS_TOKEN_TTL,
    }
    refresh_claims = {
        "sub": user["id"],
        "forge.tenant": tenant["id"],
        "type": _TOKEN_TYPE_REFRESH,
        "iat": now,
        "exp": now + _REFRESH_TOKEN_TTL,
    }
    forge_access = jwt.encode(
        access_claims,
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )
    forge_refresh = jwt.encode(
        refresh_claims,
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    # step-65: RS256 proxy_token for the LiteLLM Proxy.  Signed once
    # at login, cached in Redis against the access-token fingerprint
    # so subsequent routes can recover it without re-signing.
    proxy_token_value = issue_proxy_token(
        user_id=user["id"],
        email=user["email"],
        tenant_id=tenant["id"],
        project_id=None,
        roles=[user["role"]],
    )
    await proxy_token_cache.store(
        forge_access,
        proxy_token_value,
        ttl_seconds=int(_ACCESS_TOKEN_TTL.total_seconds()),
    )

    logger.info(
        "auth.oidc.success",
        user_id=user["id"],
        tenant_id=tenant["id"],
        role=user["role"],
    )

    return TokenResponse(
        access_token=forge_access,
        refresh_token=forge_refresh,
        proxy_token=proxy_token_value,
        user=user,
        tenant=tenant,
    )
@require_approval_phase(SDLCPhase.PLANNING)


@router.post("/refresh", response_model=AccessTokenResponse)
async def refresh(req: RefreshRequest) -> AccessTokenResponse:
    """Trade a Forge refresh token for a fresh access token.

    Returns 401 (``not_a_refresh_token`` / ``invalid_refresh_token``) on
    any failure. The frontend treats both as "kick the user back to
    /login" — there's no recovery flow that doesn't require the user to
    re-authenticate through Keycloak.
    """
    try:
        payload = decode_token(req.refresh_token)
    except HTTPException:
        # decode_token already shaped the error as 401; re-raise.
        raise

    if payload.get("type") != _TOKEN_TYPE_REFRESH:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="not_a_refresh_token",
        )

    user_id = payload.get("sub")
    tenant_id = payload.get("forge.tenant") or payload.get("tenant_id")
    if not user_id or not tenant_id:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid_refresh_token",
        )

    # Confirm the principal still exists in this tenant. A deleted user
    # shouldn't be able to keep refreshing forever.
    factory = get_session_factory()
    async with factory() as session:
        user = await get_user_by_id(session, user_id=user_id, tenant_id=tenant_id)
    if user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid_refresh_token",
        )

    now = datetime.now(tz=timezone.utc)
    access_claims = {
        "sub": user["id"],
        "email": user["email"],
        "forge.tenant": tenant_id,
        "role": user["role"],
        "type": _TOKEN_TYPE_ACCESS,
        "iat": now,
        "exp": now + _ACCESS_TOKEN_TTL,
    }
    forge_access = jwt.encode(
        access_claims,
        settings.jwt_secret,
        algorithm=settings.jwt_algorithm,
    )

    # step-65: re-issue the proxy_token alongside the access token so
    # the LiteLLM Proxy keeps trusting the user after a refresh.
    proxy_token_value = issue_proxy_token(
        user_id=user["id"],
        email=user["email"],
        tenant_id=tenant_id,
        project_id=None,
        roles=[user["role"]],
    )
    await proxy_token_cache.store(
        forge_access,
        proxy_token_value,
        ttl_seconds=int(_ACCESS_TOKEN_TTL.total_seconds()),
    )

    return AccessTokenResponse(
        access_token=forge_access,
        proxy_token=proxy_token_value,
    )
@require_approval_phase(SDLCPhase.PLANNING)


@router.post("/logout")
async def logout(
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
) -> None:
    """Revoke the cached proxy_token (step-65).

    The Forge access token itself is stateless (HMAC) and can't be
    revoked server-side; the SPA also drops it from localStorage in
    the matching client-side handler.  The proxy_token has a
    server-side Redis cache; without invalidation a logged-out user's
    RS256 token keeps working until its 1-hour TTL.

    ponytail: passing the raw bearer through ``get_current_principal``
    is the only way to fingerprint the cache key here, and the load
    path doesn't justify the plumbing for a 1-hour bounded leak.  Log
    the logout (audit captures it) and let the Redis TTL handle the
    window.  If precise revocation becomes a requirement, swap the
    dependency for a custom one that yields ``(principal, bearer)``.
    """
    logger.info(
        "auth.logout",
        user_id=principal.user_id,
        tenant_id=principal.tenant_id,
    )
    return Response()


@router.get("/jwks.json", include_in_schema=False)
async def proxy_token_jwks() -> dict[str, Any]:
    """Expose the backend's RS256 public key as a JWKS document.

    step-65 — the LiteLLM Proxy fetches this URL (``JWT_PUBLIC_KEY_URL``)
    to validate the RS256 ``proxy_token`` we issue at login.  No
    auth required: the document contains the public key only, and
    rotating the keypair invalidates every cached token (a
    deliberate, scheduled event).
    """
    from jose.utils import long_to_base64
    from cryptography.hazmat.primitives import serialization

    from app.core.oauth2_rsa import _load_or_generate  # module-private but safe

    _, pub_pem = _load_or_generate()
    pub_key = serialization.load_pem_public_key(pub_pem)
    numbers = pub_key.public_numbers()
    # RSA n and e encoded as base64url — the standard JWKS format.
    n_b64 = long_to_base64(numbers.n).decode("ascii")
    e_b64 = long_to_base64(numbers.e).decode("ascii")
    return {
        "keys": [
            {
                "kty": "RSA",
                "alg": "RS256",
                "use": "sig",
                "kid": "forge-proxy-1",
                "n": n_b64,
                "e": e_b64,
            }
        ]
    }


@router.get("/me")
async def get_me(
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
) -> dict[str, Any]:
    """Return the principal backing the current bearer token.

    Mirrors ``POST /auth/oidc/callback``'s ``user`` shape so the
    frontend can treat them as the same type.
    """
    factory = get_session_factory()
    async with factory() as session:
        user = await get_user_by_id(
            session, user_id=principal.user_id, tenant_id=principal.tenant_id
        )
    if user is None:
        # Token decoded but the row was deleted — treat as 401 so the
        # frontend's refresh + retry loop will surface "session ended".
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="user_not_found",
        )
    return user
@require_approval_phase(SDLCPhase.PLANNING)


@router.patch("/me", response_model=dict[str, Any])
async def patch_me(
    body: UserProfileUpdate,
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
) -> dict[str, Any]:
    """Self-service profile update (Settings → Profile).

    Writes to ``User.profile`` JSONB. Only the four typed fields above
    are honored; anything else in ``body`` is rejected by Pydantic so a
    typo doesn't silently persist.

    Two-PATCHer: actually we don't touch ``User.display_name`` here
    because Keycloak owns it on login. The four JSONB fields are the
    *Forge-specific* overrides. The frontend reads them as the source
    of truth and falls back to ``display_name`` if unset.

    Permission: principal auth only — users can edit their own profile.
    """
    from app.db.models.user import User as UserModel

    factory = get_session_factory()
    async with factory() as session:
        user_row = await session.get(UserModel, principal.user_id)
        if user_row is None:
            raise HTTPException(status_code=404, detail="user_not_found")
        profile = dict(user_row.profile or {})
        # PATCH semantics — only fields explicitly set overwrite.
        update = body.model_dump(exclude_unset=True)
        if "display_name" in update and update["display_name"] is not None:
            profile["display_name"] = update["display_name"]
            user_row.display_name = update["display_name"]
        if "avatar_url" in update:
            profile["avatar_url"] = update["avatar_url"]
        if "locale" in update:
            profile["locale"] = update["locale"]
        if "timezone" in update:
            profile["timezone"] = update["timezone"]
        user_row.profile = profile
        await session.commit()
        await session.refresh(user_row)

    logger.info(
        "auth.me.profile_updated",
        user_id=principal.user_id,
        fields=list(update.keys()),
    )
    return {
        "id": str(user_row.id),
        "email": user_row.email,
        "display_name": user_row.display_name,
        "avatar_url": profile.get("avatar_url"),
        "locale": profile.get("locale"),
        "timezone": profile.get("timezone"),
        "role_ids": [str(r) for r in (user_row.role_ids or [])],
    }


@router.get("/sso/config", response_model=SsoConfigRead)
async def get_sso_config() -> SsoConfigRead:
    """Read-only SSO config (Settings → SSO).

    Env-driven. Returns ``enabled=False`` when OIDC is not configured.
    Never exposes client secrets.

    ponytail: read-only env-var projection, no service extraction. If
    this surface gains per-tenant overrides later, move to
    ``app/services/sso_config.py``.
    """
    issuer: str | None = None
    if settings.keycloak_url and settings.keycloak_realm:
        issuer = (
            f"{settings.keycloak_url.rstrip('/')}/realms/{settings.keycloak_realm}"
        )
    client_id = getattr(settings, "keycloak_client_id", None) or "forge-ui"
    scopes_raw = getattr(settings, "oidc_scopes", None) or "openid profile email"
    return SsoConfigRead(
        enabled=bool(issuer),
        provider="keycloak",
        issuer=issuer,
        client_id=client_id,
        scopes=[s.strip() for s in scopes_raw.split() if s.strip()],
    )


@router.get("/me/tenants")
async def list_my_tenants(
    principal: AuthenticatedPrincipal = Depends(get_current_principal),
) -> list[dict[str, Any]]:
    """List every tenant the calling user belongs to (step-61 Zone 1).

    Powers the ``TenantSwitcher`` dropdown in the top bar. A user can
    belong to more than one tenant — for example, an admin who
    manages the company workspace AND a separate ``acme-sandbox``
    workspace for prototyping. The JWT carries the *currently active*
    tenant; this endpoint surfaces the full set so the UI can render
    a switcher.

    Lookup strategy (no dedicated ``TenantMember`` join table yet):
      * Find every ``User`` row whose email matches the JWT's email.
        Same person, possibly mirrored into several tenants by
        repeated OIDC bootstrap (different Keycloak attributes each
        time).
      * Project the matching ``Tenant`` rows; deduplicate by id;
        mark the JWT's tenant as ``is_current``.

    A more sophisticated TenantMember join is on the roadmap; until
    then this lookup is correct for the demo realm's user-pooling.
    """
    email = principal.email
    if not email:
        # Defensive: a token without an email claim can't be cross-
        # referenced. Fall back to the principal's single tenant so
        # the dropdown still has something to show.
        factory = get_session_factory()
        async with factory() as session:
            tenant = await session.get(Tenant, _coerce_tenant_id(principal.tenant_id))
        if tenant is None:
            return []
        settings = dict(tenant.settings or {})
        return [
            {
                "id": str(tenant.id),
                "name": tenant.name,
                "slug": tenant.slug,
                "plan": settings.get("plan", "free"),
                "region": settings.get("region", "us-east-1"),
                "logo_url": settings.get("logo_url"),
                "role": "member",
                "is_current": True,
            }
        ]

    factory = get_session_factory()
    async with factory() as session:
        # All User rows (any tenant) sharing this email.
        user_rows = (
            await session.execute(select(User).where(User.email == email))
        ).scalars().all()
        tenant_ids = {u.tenant_id for u in user_rows}
        if not tenant_ids:
            return []
        tenants = (
            await session.execute(
                select(Tenant).where(Tenant.id.in_(tenant_ids))
            )
        ).scalars().all()

    # Index by tenant-id for current-tenant detection + role lookup.
    current_tenant_uuid = _coerce_tenant_id(principal.tenant_id)
    users_by_tenant: dict[Any, User] = {u.tenant_id: u for u in user_rows}

    results: list[dict[str, Any]] = []
    for tenant in tenants:
        settings = dict(tenant.settings or {})
        user_in_tenant = users_by_tenant.get(tenant.id)
        role = (
            (user_in_tenant.profile or {}).get("role", "member")
            if user_in_tenant is not None
            else "member"
        )
        results.append(
            {
                "id": str(tenant.id),
                "name": tenant.name,
                "slug": tenant.slug,
                "plan": settings.get("plan", "free"),
                "region": settings.get("region", "us-east-1"),
                "logo_url": settings.get("logo_url"),
                "role": role,
                "is_current": tenant.id == current_tenant_uuid,
            }
        )

    # Current tenant first, then alphabetical.
    results.sort(key=lambda t: (not t["is_current"], t["name"]))
    return results


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _keycloak_jwks_url() -> str:
    return (
        f"{settings.keycloak_url}/realms/{settings.keycloak_realm}"
        "/protocol/openid-connect/certs"
    )


# Cache the JWKS in-process so every callback doesn't refetch the key set.
# The cache lives for the lifetime of the backend process; Keycloak rotates
# keys rarely (and the rotation triggers a /realms/.../certs cache miss
# that we re-fetch on the next login — at worst, one user pays the cost
# of the fetch, everyone else gets the cached keys).
_JWKS_CACHE: dict[str, Any] = {"keys": None, "fetched_at": 0.0}
_JWKS_CACHE_TTL_SECONDS = 300.0


async def _get_jwks() -> list[dict[str, Any]]:
    """Return the cached Keycloak JWKS, refreshing at most every 5 min."""
    import time

    now = time.monotonic()
    if _JWKS_CACHE["keys"] is not None and (now - _JWKS_CACHE["fetched_at"]) < _JWKS_CACHE_TTL_SECONDS:
        return _JWKS_CACHE["keys"]

    async with httpx.AsyncClient(timeout=10.0) as client:
        resp = await client.get(_keycloak_jwks_url())
    if resp.status_code != 200:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="oidc_provider_unavailable",
        )
    keys = resp.json().get("keys", [])
    _JWKS_CACHE["keys"] = keys
    _JWKS_CACHE["fetched_at"] = now
    return keys


async def _decode_keycloak_id_token(id_token: str) -> dict[str, Any]:
    """Verify an OIDC ID token signature + decode its claims.

    Validation steps:
      1. Fetch Keycloak's JWKS (cached).
      2. Locate the key whose ``kid`` matches the ID token header's
         ``kid``.
      3. Verify the signature using ``python-jose`` against that key.
      4. Reject if ``aud`` doesn't include ``forge-ui`` (defends against
         an attacker swapping in a token issued for a different client).
      5. Reject if ``iss`` doesn't end with
         ``/realms/{realm}`` (defends against cross-realm token replay).

    Issuer matching is **path-based** rather than full-string, because
    the browser hits Keycloak via ``http://localhost:8080`` while the
    backend hits it via ``http://keycloak:8080``. Same realm, two
    hostnames; Keycloak happily issues tokens with the request's
    effective issuer. Strict full-string match would falsely reject
    browser-issued tokens.
    """
    try:
        header = jwt.get_unverified_header(id_token)
        kid = header.get("kid")
        if not kid:
            raise JWTError("missing kid")
        keys = await _get_jwks()
        key = next((k for k in keys if k.get("kid") == kid), None)
        if key is None:
            raise JWTError(f"no JWKS key for kid={kid}")
        # Disable jose's built-in issuer check; we do path-based
        # validation below.
        claims = jwt.decode(
            id_token,
            key,
            algorithms=[key.get("alg", "RS256")],
            audience="forge-ui",
            options={
                "verify_at_hash": False,
                "verify_iss": False,
            },
        )
        # Path-based issuer check: must end with /realms/{realm}.
        iss = claims.get("iss", "")
        expected_suffix = f"/realms/{settings.keycloak_realm}"
        if not (isinstance(iss, str) and iss.endswith(expected_suffix)):
            raise JWTError(f"Invalid issuer: {iss!r}")
    except JWTError as exc:
        logger.warning("auth.oidc.invalid_id_token", error=str(exc))
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="invalid_id_token",
        ) from exc

    return claims


def _first_attr(userinfo: dict[str, Any], key: str) -> str | None:
    """Return the first value of a Keycloak user attribute.

    Keycloak user attributes come back as lists (even single-valued
    ones) so we collapse to the head element when present. Returns
    ``None`` for absent / empty values so the caller can apply
    fallbacks.
    """
    value = userinfo.get(key)
    if isinstance(value, list):
        return value[0] if value else None
    return value or None


# Re-export for tests + ad-hoc imports.
__all__ = [
    "router",
    "OIDCCallbackRequest",
    "TokenResponse",
    "RefreshRequest",
    "AccessTokenResponse",
    "_decode_keycloak_id_token",
]
