"""
Schemas for the DevOps Agent handoff contract.

This follows the Epic 6 DevOps Stage Plan (FORA-22).
"""

from __future__ import annotations

import datetime as dt
import hashlib
import uuid
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

SCHEMA_VERSION = "1.0.0"

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class ArtifactStatus(str, Enum):
    PENDING = "pending"
    GENERATED = "generated"
    FAILED = "failed"
    SKIPPED = "skipped"

class DeployStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    ROLLBACK = "rollback"
    PAUSED = "paused"
    CANCELLED = "cancelled"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")

# ---------------------------------------------------------------------------
# 6.1 Artifact Generation Schemas
# ---------------------------------------------------------------------------

@dataclass
class Artifact:
    """A single artifact generated by the agent."""
    path: str
    kind: str  # "dockerfile", "terraform", "helm", "github_actions", "argocd", "runbook"
    status: str
    diff_hash: Optional[str] = None
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class ArtifactSet:
    """The collection of artifacts generated for a service."""
    schema_version: str
    run_id: str
    tenant_id: str
    service: str
    artifacts: List[Artifact] = field(default_factory=list)
    github_pr_url: Optional[str] = None
    generated_at: str = field(default_factory=_now)

    def to_dict(self) -> Dict[str, Any]:
        out = asdict(self)
        out["artifacts"] = [a.to_dict() for a in self.artifacts]
        return out

# ---------------------------------------------------------------------------
# 6.2 Deployment Schemas
# ---------------------------------------------------------------------------

@dataclass
class DeployPlan:
    """Input for the deployment stage (6.2)."""
    schema_version: str
    run_id: str
    tenant_id: str
    env: str  # "dev", "staging", "prod"
    service: str
    image_tag: str
    helm_overrides: Dict[str, Any] = field(default_factory=dict)
    rollback_target: Optional[str] = None
    needs_cto_approval: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class DeployRun:
    """Outcome of a deployment execution."""
    schema_version: str
    run_id: str
    status: str
    started_at: str = field(default_factory=_now)
    finished_at: Optional[str] = None
    approver_id: Optional[str] = None
    verification_smoke_passed: bool = False
    audit_log_entry_id: Optional[str] = None
    notes: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

# ---------------------------------------------------------------------------
# ID factories
# ---------------------------------------------------------------------------

def new_artifact_set_id() -> str:
    return f"art-{uuid.uuid4().hex[:12]}"

def new_deploy_run_id() -> str:
    return f"dep-{uuid.uuid4().hex[:12]}"

__all__ = [
    "SCHEMA_VERSION",
    "ArtifactStatus",
    "DeployStatus",
    "Artifact",
    "ArtifactSet",
    "DeployPlan",
    "DeployRun",
    "new_artifact_set_id",
    "new_deploy_run_id",
]
