"""initial_baseline

Revision ID: a795c2f979da
Revises: 
Create Date: 2026-06-24 10:07:15.723096

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.db.base import GUID, JSONB, ARRAY  # noqa: E402


# revision identifiers, used by Alembic.
revision: str = 'a795c2f979da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('CLAUDE_CODE', 'CODEX', 'GEMINI', 'CUSTOM', name='agent_type'), nullable=False),
    sa.Column('capabilities', JSONB(), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', 'DEPRECATED', name='agent_status'), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_index('ix_agents_tenant_project_status', 'agents', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_index('ix_agents_tenant_type', 'agents', ['tenant_id', 'type'], unique=False)
    op.create_table('artifacts',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', 'ARCHIVED', name='artifact_status'), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('superseded_by_id', GUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['artifacts.id'], name=op.f('fk_artifacts_superseded_by_id_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_content_hash'), 'artifacts', ['content_hash'], unique=False)
    op.create_index('ix_artifacts_tenant_project_type_status', 'artifacts', ['tenant_id', 'project_id', 'type', 'status'], unique=False)
    op.create_index('ix_artifacts_tenant_type', 'artifacts', ['tenant_id', 'type'], unique=False)
    op.create_table('audit_events',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('payload', JSONB(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_project_id'), 'audit_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_events_target_type'), 'audit_events', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('connectors',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('GITHUB', 'JIRA', 'CONFLUENCE', 'FIGMA', 'AWS', 'SLACK', 'SONARQUBE', 'DATABRICKS', 'AZURE_DEVOPS', 'CLICKUP', 'ZENDESK', 'SECRETS', name='connector_type'), nullable=False),
    sa.Column('config', JSONB(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SYNCING', 'HEALTHY', 'STALE', 'QUARANTINED', 'FAILED', name='connector_status'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connectors'))
    )
    op.create_index(op.f('ix_connectors_project_id'), 'connectors', ['project_id'], unique=False)
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_index('ix_connectors_tenant_project_type', 'connectors', ['tenant_id', 'project_id', 'type'], unique=False)
    op.create_index('ix_connectors_tenant_status', 'connectors', ['tenant_id', 'status'], unique=False)
    op.create_table('cost_entries',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('workflow_id', GUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_entries'))
    )
    op.create_index(op.f('ix_cost_entries_recorded_at'), 'cost_entries', ['recorded_at'], unique=False)
    op.create_index('ix_cost_project_recorded', 'cost_entries', ['project_id', 'recorded_at'], unique=False)
    op.create_index('ix_cost_tenant_model', 'cost_entries', ['tenant_id', 'model'], unique=False)
    op.create_index('ix_cost_tenant_recorded', 'cost_entries', ['tenant_id', 'recorded_at'], unique=False)
    op.create_table('hooks',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('phase', sa.Enum('PRE', 'POST', 'ERROR', name='hook_phase'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_order', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hooks'))
    )
    op.create_index(op.f('ix_hooks_event_type'), 'hooks', ['event_type'], unique=False)
    op.create_index(op.f('ix_hooks_project_id'), 'hooks', ['project_id'], unique=False)
    op.create_index('ix_hooks_tenant_event_enabled', 'hooks', ['tenant_id', 'event_type', 'enabled'], unique=False)
    op.create_index(op.f('ix_hooks_tenant_id'), 'hooks', ['tenant_id'], unique=False)
    op.create_table('ideas',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('USER', 'COMMUNITY', 'SIGNAL', 'ROADMAP', 'FEEDBACK', name='idea_source'), nullable=False),
    sa.Column('submitted_by', GUID(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ANALYZING', 'SCORED', 'APPROVED', 'IN_ROADMAP', 'REJECTED', 'ARCHIVED', name='idea_status'), nullable=False),
    sa.Column('tags', JSONB(), nullable=False),
    sa.Column('attachments', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas'))
    )
    op.create_index(op.f('ix_ideas_project_id'), 'ideas', ['project_id'], unique=False)
    op.create_index(op.f('ix_ideas_submitted_by'), 'ideas', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_ideas_tenant_id'), 'ideas', ['tenant_id'], unique=False)
    op.create_index('ix_ideas_tenant_project_status', 'ideas', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_index('ix_ideas_tenant_submitted_by', 'ideas', ['tenant_id', 'submitted_by'], unique=False)
    op.create_table('marketplace_connectors',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config_schema', JSONB(), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplace_connectors'))
    )
    op.create_index(op.f('ix_marketplace_connectors_slug'), 'marketplace_connectors', ['slug'], unique=True)
    op.create_index(op.f('ix_marketplace_connectors_type'), 'marketplace_connectors', ['type'], unique=False)
    op.create_index('ix_marketplace_type', 'marketplace_connectors', ['type'], unique=False)
    op.create_table('model_providers',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('ANTHROPIC', 'OPENAI', 'GOOGLE', 'BEDROCK', 'AZURE_OPENAI', 'CUSTOM', name='model_provider_type'), nullable=False),
    sa.Column('config', JSONB(), nullable=False),
    sa.Column('litellm_model_alias', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=False),
    sa.Column('rate_limit_tpm', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_providers'))
    )
    op.create_index('ix_model_providers_tenant_enabled', 'model_providers', ['tenant_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_model_providers_tenant_id'), 'model_providers', ['tenant_id'], unique=False)
    op.create_index('uq_model_providers_tenant_alias', 'model_providers', ['tenant_id', 'litellm_model_alias'], unique=True)
    op.create_table('onboarding_sessions',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='onboarding_status'), nullable=False),
    sa.Column('current_step', sa.String(length=64), nullable=False),
    sa.Column('state', JSONB(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_sessions'))
    )
    op.create_index(op.f('ix_onboarding_sessions_project_id'), 'onboarding_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_tenant_id'), 'onboarding_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_onboarding_sessions_tenant_project', 'onboarding_sessions', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_onboarding_sessions_user_id'), 'onboarding_sessions', ['user_id'], unique=False)
    op.create_table('policies',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('expression', JSONB(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'BLOCK', name='policy_severity'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_index('ix_policies_tenant_enabled', 'policies', ['tenant_id', 'enabled'], unique=False)
    op.create_table('repos',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('ingestion_status', sa.Enum('PENDING', 'CLONING', 'EXTRACTING', 'GRAPHIFYING', 'MAPPING', 'PERSISTING', 'SUCCESS', 'FAILED', 'CANCELLED', name='repo_ingestion_status'), nullable=False),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=200), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repos'))
    )
    op.create_index(op.f('ix_repos_project_id'), 'repos', ['project_id'], unique=False)
    op.create_index(op.f('ix_repos_tenant_id'), 'repos', ['tenant_id'], unique=False)
    op.create_index('ix_repos_tenant_project', 'repos', ['tenant_id', 'project_id'], unique=False)
    op.create_index('ix_repos_tenant_status', 'repos', ['tenant_id', 'ingestion_status'], unique=False)
    op.create_table('roadmaps',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('horizon', sa.Enum('NOW', 'NEXT', 'LATER', 'FUTURE', name='roadmap_horizon'), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROPOSED', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='roadmap_status'), nullable=False),
    sa.Column('items', JSONB(), nullable=False),
    sa.Column('generated_by', GUID(), nullable=False),
    sa.Column('approved_by', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmaps'))
    )
    op.create_index(op.f('ix_roadmaps_project_id'), 'roadmaps', ['project_id'], unique=False)
    op.create_index('ix_roadmaps_tenant_horizon', 'roadmaps', ['tenant_id', 'horizon'], unique=False)
    op.create_index(op.f('ix_roadmaps_tenant_id'), 'roadmaps', ['tenant_id'], unique=False)
    op.create_index('ix_roadmaps_tenant_project_status', 'roadmaps', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settings', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('terminal_session_costs',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('command_count', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminal_session_costs'))
    )
    op.create_index(op.f('ix_terminal_session_costs_recorded_at'), 'terminal_session_costs', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_terminal_session_costs_session_id'), 'terminal_session_costs', ['session_id'], unique=False)
    op.create_index('ix_tsc_session_model', 'terminal_session_costs', ['session_id', 'model'], unique=False)
    op.create_index('ix_tsc_tenant_recorded', 'terminal_session_costs', ['tenant_id', 'recorded_at'], unique=False)
    op.create_table('workflow_budget_decisions',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('workflow_id', GUID(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('projected_cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('ceiling_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('actor_id', GUID(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_budget_decisions'))
    )
    op.create_index(op.f('ix_workflow_budget_decisions_occurred_at'), 'workflow_budget_decisions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_workflow_budget_decisions_project_id'), 'workflow_budget_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_budget_decisions_tenant_id'), 'workflow_budget_decisions', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_budget_decisions_workflow', 'workflow_budget_decisions', ['workflow_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_workflow_budget_decisions_workflow_id'), 'workflow_budget_decisions', ['workflow_id'], unique=False)
    op.create_table('workflow_budgets',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('workflow_id', GUID(), nullable=False),
    sa.Column('ceiling_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXHAUSTED', 'CLOSED', name='workflow_budget_status'), nullable=False),
    sa.Column('declared_by', GUID(), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_budgets')),
    sa.UniqueConstraint('workflow_id', name=op.f('uq_workflow_budgets_workflow_id'))
    )
    op.create_index(op.f('ix_workflow_budgets_project_id'), 'workflow_budgets', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_budgets_tenant_id'), 'workflow_budgets', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_budgets_tenant_project', 'workflow_budgets', ['tenant_id', 'project_id'], unique=False)
    op.create_table('workflows',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', JSONB(), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('latest_run_id', GUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows')),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name', name='uq_workflows_tenant_project_name')
    )
    op.create_index('ix_workflows_tenant_project', 'workflows', ['tenant_id', 'project_id'], unique=False)
    op.create_index('ix_workflows_tenant_project_deleted', 'workflows', ['tenant_id', 'project_id', 'deleted_at'], unique=False)
    op.create_table('approval_requests',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('target_artifact_id', GUID(), nullable=True),
    sa.Column('requested_by', GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GRANTED', 'DENIED', 'EXPIRED', 'CANCELLED', name='approval_status'), nullable=False),
    sa.Column('decided_by', GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['artifacts.id'], name=op.f('fk_approval_requests_target_artifact_id_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_type'), 'approval_requests', ['type'], unique=False)
    op.create_index('ix_approvals_tenant_project_status', 'approval_requests', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_table('architecture_previews',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('components', JSONB(), nullable=False),
    sa.Column('integrations', JSONB(), nullable=False),
    sa.Column('data_flows', JSONB(), nullable=False),
    sa.Column('risks', JSONB(), nullable=False),
    sa.Column('generated_by', GUID(), nullable=False),
    sa.Column('superseded_by_id', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_architecture_previews_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_architecture_previews'))
    )
    op.create_index('ix_arch_previews_idea', 'architecture_previews', ['idea_id'], unique=False)
    op.create_index('ix_arch_previews_tenant_project', 'architecture_previews', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_architecture_previews_idea_id'), 'architecture_previews', ['idea_id'], unique=False)
    op.create_index(op.f('ix_architecture_previews_project_id'), 'architecture_previews', ['project_id'], unique=False)
    op.create_index(op.f('ix_architecture_previews_tenant_id'), 'architecture_previews', ['tenant_id'], unique=False)
    op.create_table('connector_sync_history',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('connector_id', GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILURE', 'TIMEOUT', name='sync_status'), nullable=False),
    sa.Column('items_synced', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], name=op.f('fk_connector_sync_history_connector_id_connectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_sync_history'))
    )
    op.create_index(op.f('ix_connector_sync_history_connector_id'), 'connector_sync_history', ['connector_id'], unique=False)
    op.create_index(op.f('ix_connector_sync_history_project_id'), 'connector_sync_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_connector_sync_history_tenant_id'), 'connector_sync_history', ['tenant_id'], unique=False)
    op.create_index('ix_sync_history_connector_started', 'connector_sync_history', ['connector_id', 'started_at'], unique=False)
    op.create_table('idea_analyses',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('target_users', JSONB(), nullable=False),
    sa.Column('success_metrics', JSONB(), nullable=False),
    sa.Column('assumptions', JSONB(), nullable=False),
    sa.Column('risks', JSONB(), nullable=False),
    sa.Column('related_artifacts', JSONB(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_analyses_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_analyses'))
    )
    op.create_index('ix_idea_analyses_idea', 'idea_analyses', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_analyses_idea_id'), 'idea_analyses', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_analyses_project_id'), 'idea_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_idea_analyses_tenant_id'), 'idea_analyses', ['tenant_id'], unique=False)
    op.create_index('ix_idea_analyses_tenant_project', 'idea_analyses', ['tenant_id', 'project_id'], unique=False)
    op.create_table('ideation_approval_items',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('request_type', sa.Enum('ROADMAP', 'PRD', 'ARCH_PREVIEW', 'PUSH_TO_DELIVERY', name='approval_item_type'), nullable=False),
    sa.Column('subject_id', GUID(), nullable=True),
    sa.Column('payload', JSONB(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'REQUEST_CHANGES', 'DELEGATED', 'CANCELLED', name='approval_item_status'), nullable=False),
    sa.Column('requested_by', GUID(), nullable=False),
    sa.Column('reviewer_id', GUID(), nullable=True),
    sa.Column('decided_by', GUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_ideation_approval_items_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideation_approval_items'))
    )
    op.create_index('ix_approval_items_idea_type', 'ideation_approval_items', ['idea_id', 'request_type'], unique=False)
    op.create_index('ix_approval_items_tenant_reviewer_status', 'ideation_approval_items', ['tenant_id', 'reviewer_id', 'status'], unique=False)
    op.create_index(op.f('ix_ideation_approval_items_idea_id'), 'ideation_approval_items', ['idea_id'], unique=False)
    op.create_index(op.f('ix_ideation_approval_items_project_id'), 'ideation_approval_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_ideation_approval_items_tenant_id'), 'ideation_approval_items', ['tenant_id'], unique=False)
    op.create_table('ideation_push_records',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('target', sa.Enum('JIRA', 'CONFLUENCE', 'ARCHITECTURE', name='push_target'), nullable=False),
    sa.Column('external_ref', sa.String(length=512), nullable=True),
    sa.Column('config', JSONB(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', name='push_status'), nullable=False),
    sa.Column('actor_id', GUID(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_ideation_push_records_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideation_push_records'))
    )
    op.create_index(op.f('ix_ideation_push_records_idea_id'), 'ideation_push_records', ['idea_id'], unique=False)
    op.create_index(op.f('ix_ideation_push_records_project_id'), 'ideation_push_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_ideation_push_records_tenant_id'), 'ideation_push_records', ['tenant_id'], unique=False)
    op.create_index('ix_push_records_idea_target', 'ideation_push_records', ['idea_id', 'target'], unique=False)
    op.create_index('ix_push_records_tenant_status', 'ideation_push_records', ['tenant_id', 'status'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('repo_id', GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'EXTRACTING', 'GRAPHIFYING', 'MAPPING', 'PERSISTING', 'SUCCESS', 'FAILED', 'CANCELLED', name='ingestion_run_status'), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('artifacts_produced', JSONB(), nullable=False),
    sa.Column('started_by', GUID(), nullable=False),
    sa.Column('started_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('finished_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], name=op.f('fk_ingestion_runs_repo_id_repos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_project_id'), 'ingestion_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_repo_id'), 'ingestion_runs', ['repo_id'], unique=False)
    op.create_index('ix_ingestion_runs_repo_started', 'ingestion_runs', ['repo_id', 'started_at'], unique=False)
    op.create_index('ix_ingestion_runs_status', 'ingestion_runs', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_tenant_id'), 'ingestion_runs', ['tenant_id'], unique=False)
    op.create_table('onboarding_steps',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'FAILED', name='onboarding_step_status'), nullable=False),
    sa.Column('input', JSONB(), nullable=False),
    sa.Column('output', JSONB(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['onboarding_sessions.id'], name=op.f('fk_onboarding_steps_session_id_onboarding_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_steps'))
    )
    op.create_index(op.f('ix_onboarding_steps_session_id'), 'onboarding_steps', ['session_id'], unique=False)
    op.create_index('ix_onboarding_steps_session_order', 'onboarding_steps', ['session_id', 'step_order'], unique=False)
    op.create_index(op.f('ix_onboarding_steps_tenant_id'), 'onboarding_steps', ['tenant_id'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('value_score', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reach_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('scoring_rationale', sa.Text(), nullable=False),
    sa.Column('scored_by', sa.Enum('AI', 'HUMAN', 'HYBRID', name='score_source'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_opportunity_scores_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores'))
    )
    op.create_index('ix_opportunity_scores_idea', 'opportunity_scores', ['idea_id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_idea_id'), 'opportunity_scores', ['idea_id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_project_id'), 'opportunity_scores', ['project_id'], unique=False)
    op.create_index(op.f('ix_opportunity_scores_tenant_id'), 'opportunity_scores', ['tenant_id'], unique=False)
    op.create_index('ix_opportunity_scores_tenant_project_total', 'opportunity_scores', ['tenant_id', 'project_id', 'total_score'], unique=False)
    op.create_table('output_bundles',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('bundle', JSONB(), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_output_bundles_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_output_bundles'))
    )
    op.create_index('ix_output_bundles_idea', 'output_bundles', ['idea_id'], unique=False)
    op.create_index(op.f('ix_output_bundles_idea_id'), 'output_bundles', ['idea_id'], unique=False)
    op.create_index(op.f('ix_output_bundles_project_id'), 'output_bundles', ['project_id'], unique=False)
    op.create_index(op.f('ix_output_bundles_tenant_id'), 'output_bundles', ['tenant_id'], unique=False)
    op.create_table('prds',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', JSONB(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='prd_status'), nullable=False),
    sa.Column('generated_by', GUID(), nullable=False),
    sa.Column('reviewed_by', GUID(), nullable=True),
    sa.Column('superseded_by_id', GUID(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_prds_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prds'))
    )
    op.create_index('ix_prds_idea', 'prds', ['idea_id'], unique=False)
    op.create_index(op.f('ix_prds_idea_id'), 'prds', ['idea_id'], unique=False)
    op.create_index(op.f('ix_prds_project_id'), 'prds', ['project_id'], unique=False)
    op.create_index(op.f('ix_prds_tenant_id'), 'prds', ['tenant_id'], unique=False)
    op.create_index('ix_prds_tenant_project_status', 'prds', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settings', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions', ARRAY(), nullable=False),
    sa.Column('parent_role_id', GUID(), nullable=True),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_role_id'], ['roles.id'], name=op.f('fk_roles_parent_role_id_roles')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_roles_tenant_name')
    )
    op.create_index('ix_roles_tenant', 'roles', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('role_ids', ARRAY(), nullable=False),
    sa.Column('profile', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('workflow_id', GUID(), nullable=False),
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING_APPROVAL', 'PAUSED', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='workflow_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', GUID(), nullable=False),
    sa.Column('current_step_id', sa.String(length=64), nullable=True),
    sa.Column('state', JSONB(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_runs_workflow_id_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_index('ix_workflow_runs_status', 'workflow_runs', ['status'], unique=False)
    op.create_index('ix_workflow_runs_tenant_project', 'workflow_runs', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_workflow_id'), 'workflow_runs', ['workflow_id'], unique=False)
    op.create_index('ix_workflow_runs_workflow_status', 'workflow_runs', ['workflow_id', 'status'], unique=False)
    op.create_table('workflow_sessions',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('idea_id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflow_session_status'), nullable=False),
    sa.Column('state', JSONB(), nullable=False),
    sa.Column('current_step', sa.String(length=120), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_workflow_sessions_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_sessions'))
    )
    op.create_index('ix_workflow_sessions_idea', 'workflow_sessions', ['idea_id'], unique=False)
    op.create_index(op.f('ix_workflow_sessions_idea_id'), 'workflow_sessions', ['idea_id'], unique=False)
    op.create_index(op.f('ix_workflow_sessions_project_id'), 'workflow_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_sessions_tenant_id'), 'workflow_sessions', ['tenant_id'], unique=False)
    op.create_index('ix_workflow_sessions_tenant_status', 'workflow_sessions', ['tenant_id', 'status'], unique=False)
    op.create_table('ingestion_artifacts',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('ingestion_run_id', GUID(), nullable=False),
    sa.Column('type', sa.Enum('REPO_TARBALL', 'REPOMIX_XML', 'GRAPHIFY_JSON', 'MAP_CODEBASE_JSON', 'KNOWLEDGE_GRAPH_SNAPSHOT', 'DEPENDENCY_GRAPH', 'SERVICE_CATALOG', 'API_CATALOG', 'DATABASE_MAP', name='ingestion_artifact_type'), nullable=False),
    sa.Column('content_ref', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_artifacts_ingestion_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_artifacts'))
    )
    op.create_index(op.f('ix_ingestion_artifacts_content_hash'), 'ingestion_artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ingestion_artifacts_ingestion_run_id'), 'ingestion_artifacts', ['ingestion_run_id'], unique=False)
    op.create_index(op.f('ix_ingestion_artifacts_project_id'), 'ingestion_artifacts', ['project_id'], unique=False)
    op.create_index('ix_ingestion_artifacts_run_type', 'ingestion_artifacts', ['ingestion_run_id', 'type'], unique=False)
    op.create_index(op.f('ix_ingestion_artifacts_tenant_id'), 'ingestion_artifacts', ['tenant_id'], unique=False)
    op.create_table('standards',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_standards_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_standards'))
    )
    op.create_index('ix_standards_tenant_project_status', 'standards', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_table('steering_rules',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('applies_to_stages', ARRAY(), nullable=False),
    sa.Column('metadata', JSONB(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_steering_rules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steering_rules'))
    )
    op.create_index(op.f('ix_steering_rules_rule_id'), 'steering_rules', ['rule_id'], unique=False)
    op.create_index(op.f('ix_steering_rules_tenant_id'), 'steering_rules', ['tenant_id'], unique=False)
    op.create_index('ix_steering_rules_tenant_project_path', 'steering_rules', ['tenant_id', 'project_id', 'file_path'], unique=False)
    op.create_index('uq_steering_rules_tenant_project_rule', 'steering_rules', ['tenant_id', 'project_id', 'rule_id'], unique=True)
    op.create_table('templates',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('content', JSONB(), nullable=False),
    sa.Column('variables', JSONB(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_templates_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index('ix_templates_tenant_type', 'templates', ['tenant_id', 'type'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('tenant_id', GUID(), nullable=False),
    sa.Column('session_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='workflow_step_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', JSONB(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workflow_sessions.id'], name=op.f('fk_workflow_steps_session_id_workflow_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps'))
    )
    op.create_index(op.f('ix_workflow_steps_session_id'), 'workflow_steps', ['session_id'], unique=False)
    op.create_index('ix_workflow_steps_session_position', 'workflow_steps', ['session_id', 'position'], unique=False)
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_index('ix_workflow_steps_session_position', table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_session_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('ix_templates_tenant_type', table_name='templates')
    op.drop_table('templates')
    op.drop_index('uq_steering_rules_tenant_project_rule', table_name='steering_rules')
    op.drop_index('ix_steering_rules_tenant_project_path', table_name='steering_rules')
    op.drop_index(op.f('ix_steering_rules_tenant_id'), table_name='steering_rules')
    op.drop_index(op.f('ix_steering_rules_rule_id'), table_name='steering_rules')
    op.drop_table('steering_rules')
    op.drop_index('ix_standards_tenant_project_status', table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_ingestion_artifacts_tenant_id'), table_name='ingestion_artifacts')
    op.drop_index('ix_ingestion_artifacts_run_type', table_name='ingestion_artifacts')
    op.drop_index(op.f('ix_ingestion_artifacts_project_id'), table_name='ingestion_artifacts')
    op.drop_index(op.f('ix_ingestion_artifacts_ingestion_run_id'), table_name='ingestion_artifacts')
    op.drop_index(op.f('ix_ingestion_artifacts_content_hash'), table_name='ingestion_artifacts')
    op.drop_table('ingestion_artifacts')
    op.drop_index('ix_workflow_sessions_tenant_status', table_name='workflow_sessions')
    op.drop_index(op.f('ix_workflow_sessions_tenant_id'), table_name='workflow_sessions')
    op.drop_index(op.f('ix_workflow_sessions_project_id'), table_name='workflow_sessions')
    op.drop_index(op.f('ix_workflow_sessions_idea_id'), table_name='workflow_sessions')
    op.drop_index('ix_workflow_sessions_idea', table_name='workflow_sessions')
    op.drop_table('workflow_sessions')
    op.drop_index('ix_workflow_runs_workflow_status', table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_workflow_id'), table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_tenant_project', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_roles_tenant', table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_prds_tenant_project_status', table_name='prds')
    op.drop_index(op.f('ix_prds_tenant_id'), table_name='prds')
    op.drop_index(op.f('ix_prds_project_id'), table_name='prds')
    op.drop_index(op.f('ix_prds_idea_id'), table_name='prds')
    op.drop_index('ix_prds_idea', table_name='prds')
    op.drop_table('prds')
    op.drop_index(op.f('ix_output_bundles_tenant_id'), table_name='output_bundles')
    op.drop_index(op.f('ix_output_bundles_project_id'), table_name='output_bundles')
    op.drop_index(op.f('ix_output_bundles_idea_id'), table_name='output_bundles')
    op.drop_index('ix_output_bundles_idea', table_name='output_bundles')
    op.drop_table('output_bundles')
    op.drop_index('ix_opportunity_scores_tenant_project_total', table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_tenant_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_project_id'), table_name='opportunity_scores')
    op.drop_index(op.f('ix_opportunity_scores_idea_id'), table_name='opportunity_scores')
    op.drop_index('ix_opportunity_scores_idea', table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index(op.f('ix_onboarding_steps_tenant_id'), table_name='onboarding_steps')
    op.drop_index('ix_onboarding_steps_session_order', table_name='onboarding_steps')
    op.drop_index(op.f('ix_onboarding_steps_session_id'), table_name='onboarding_steps')
    op.drop_table('onboarding_steps')
    op.drop_index(op.f('ix_ingestion_runs_tenant_id'), table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_status', table_name='ingestion_runs')
    op.drop_index('ix_ingestion_runs_repo_started', table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_repo_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_project_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_push_records_tenant_status', table_name='ideation_push_records')
    op.drop_index('ix_push_records_idea_target', table_name='ideation_push_records')
    op.drop_index(op.f('ix_ideation_push_records_tenant_id'), table_name='ideation_push_records')
    op.drop_index(op.f('ix_ideation_push_records_project_id'), table_name='ideation_push_records')
    op.drop_index(op.f('ix_ideation_push_records_idea_id'), table_name='ideation_push_records')
    op.drop_table('ideation_push_records')
    op.drop_index(op.f('ix_ideation_approval_items_tenant_id'), table_name='ideation_approval_items')
    op.drop_index(op.f('ix_ideation_approval_items_project_id'), table_name='ideation_approval_items')
    op.drop_index(op.f('ix_ideation_approval_items_idea_id'), table_name='ideation_approval_items')
    op.drop_index('ix_approval_items_tenant_reviewer_status', table_name='ideation_approval_items')
    op.drop_index('ix_approval_items_idea_type', table_name='ideation_approval_items')
    op.drop_table('ideation_approval_items')
    op.drop_index('ix_idea_analyses_tenant_project', table_name='idea_analyses')
    op.drop_index(op.f('ix_idea_analyses_tenant_id'), table_name='idea_analyses')
    op.drop_index(op.f('ix_idea_analyses_project_id'), table_name='idea_analyses')
    op.drop_index(op.f('ix_idea_analyses_idea_id'), table_name='idea_analyses')
    op.drop_index('ix_idea_analyses_idea', table_name='idea_analyses')
    op.drop_table('idea_analyses')
    op.drop_index('ix_sync_history_connector_started', table_name='connector_sync_history')
    op.drop_index(op.f('ix_connector_sync_history_tenant_id'), table_name='connector_sync_history')
    op.drop_index(op.f('ix_connector_sync_history_project_id'), table_name='connector_sync_history')
    op.drop_index(op.f('ix_connector_sync_history_connector_id'), table_name='connector_sync_history')
    op.drop_table('connector_sync_history')
    op.drop_index(op.f('ix_architecture_previews_tenant_id'), table_name='architecture_previews')
    op.drop_index(op.f('ix_architecture_previews_project_id'), table_name='architecture_previews')
    op.drop_index(op.f('ix_architecture_previews_idea_id'), table_name='architecture_previews')
    op.drop_index('ix_arch_previews_tenant_project', table_name='architecture_previews')
    op.drop_index('ix_arch_previews_idea', table_name='architecture_previews')
    op.drop_table('architecture_previews')
    op.drop_index('ix_approvals_tenant_project_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_type'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_workflows_tenant_project_deleted', table_name='workflows')
    op.drop_index('ix_workflows_tenant_project', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_workflow_budgets_tenant_project', table_name='workflow_budgets')
    op.drop_index(op.f('ix_workflow_budgets_tenant_id'), table_name='workflow_budgets')
    op.drop_index(op.f('ix_workflow_budgets_project_id'), table_name='workflow_budgets')
    op.drop_table('workflow_budgets')
    op.drop_index(op.f('ix_workflow_budget_decisions_workflow_id'), table_name='workflow_budget_decisions')
    op.drop_index('ix_workflow_budget_decisions_workflow', table_name='workflow_budget_decisions')
    op.drop_index(op.f('ix_workflow_budget_decisions_tenant_id'), table_name='workflow_budget_decisions')
    op.drop_index(op.f('ix_workflow_budget_decisions_project_id'), table_name='workflow_budget_decisions')
    op.drop_index(op.f('ix_workflow_budget_decisions_occurred_at'), table_name='workflow_budget_decisions')
    op.drop_table('workflow_budget_decisions')
    op.drop_index('ix_tsc_tenant_recorded', table_name='terminal_session_costs')
    op.drop_index('ix_tsc_session_model', table_name='terminal_session_costs')
    op.drop_index(op.f('ix_terminal_session_costs_session_id'), table_name='terminal_session_costs')
    op.drop_index(op.f('ix_terminal_session_costs_recorded_at'), table_name='terminal_session_costs')
    op.drop_table('terminal_session_costs')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_roadmaps_tenant_project_status', table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_tenant_id'), table_name='roadmaps')
    op.drop_index('ix_roadmaps_tenant_horizon', table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_project_id'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index('ix_repos_tenant_status', table_name='repos')
    op.drop_index('ix_repos_tenant_project', table_name='repos')
    op.drop_index(op.f('ix_repos_tenant_id'), table_name='repos')
    op.drop_index(op.f('ix_repos_project_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index('ix_policies_tenant_enabled', table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_onboarding_sessions_user_id'), table_name='onboarding_sessions')
    op.drop_index('ix_onboarding_sessions_tenant_project', table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_tenant_id'), table_name='onboarding_sessions')
    op.drop_index(op.f('ix_onboarding_sessions_project_id'), table_name='onboarding_sessions')
    op.drop_table('onboarding_sessions')
    op.drop_index('uq_model_providers_tenant_alias', table_name='model_providers')
    op.drop_index(op.f('ix_model_providers_tenant_id'), table_name='model_providers')
    op.drop_index('ix_model_providers_tenant_enabled', table_name='model_providers')
    op.drop_table('model_providers')
    op.drop_index('ix_marketplace_type', table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_type'), table_name='marketplace_connectors')
    op.drop_index(op.f('ix_marketplace_connectors_slug'), table_name='marketplace_connectors')
    op.drop_table('marketplace_connectors')
    op.drop_index('ix_ideas_tenant_submitted_by', table_name='ideas')
    op.drop_index('ix_ideas_tenant_project_status', table_name='ideas')
    op.drop_index(op.f('ix_ideas_tenant_id'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_submitted_by'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_project_id'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_hooks_tenant_id'), table_name='hooks')
    op.drop_index('ix_hooks_tenant_event_enabled', table_name='hooks')
    op.drop_index(op.f('ix_hooks_project_id'), table_name='hooks')
    op.drop_index(op.f('ix_hooks_event_type'), table_name='hooks')
    op.drop_table('hooks')
    op.drop_index('ix_cost_tenant_recorded', table_name='cost_entries')
    op.drop_index('ix_cost_tenant_model', table_name='cost_entries')
    op.drop_index('ix_cost_project_recorded', table_name='cost_entries')
    op.drop_index(op.f('ix_cost_entries_recorded_at'), table_name='cost_entries')
    op.drop_table('cost_entries')
    op.drop_index('ix_connectors_tenant_status', table_name='connectors')
    op.drop_index('ix_connectors_tenant_project_type', table_name='connectors')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_project_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_project_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_artifacts_tenant_type', table_name='artifacts')
    op.drop_index('ix_artifacts_tenant_project_type_status', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_content_hash'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_agents_tenant_type', table_name='agents')
    op.drop_index('ix_agents_tenant_project_status', table_name='agents')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###