"""Unit tests for `mcp/checkout/tools.json` (FORA-72 / v0.1 deterministic).

Generated by `agents.qa.test_generator`. Replace the body of
`test_subject_under_test_contract` with the assertions that exercise your
implementation; the v0.1 scaffold asserts only that the
import resolves.
"""

from __future__ import annotations

import importlib
import os
import sys

import pytest


# Make the module under test importable. The DevOps
# orchestrator rewrites this to the real repo root on
# publish; v0.1 leaves it as a relative `src/` hint.
_HERE = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    os.path.join(_HERE, "..", "..", "src"),
    os.path.join(_HERE, "..", "src"),
):
    if os.path.isdir(_candidate) and _candidate not in sys.path:
        sys.path.insert(0, _candidate)


def _load_target() -> object:
    """Best-effort import of the symbol under test.

    Returns the module or the symbol if the import resolves;
    returns None otherwise so the contract test is still a
    valid (if weak) starting point.
    """
    mod_path = 'mcp/checkout/tools.json'
    try:
        module = importlib.import_module(mod_path)
    except Exception:
        return None
    return getattr(module, 'subject_under_test', module)


def test_subject_under_test_contract() -> None:
    """The v0.1 contract: the symbol can be imported.

    A future pass fleshes this out with real assertions.
    """
    subject = _load_target()
    # Either we have a callable subject, or the module loads
    # (None is acceptable in v0.1 — the operator fleshes this
    # out; v0.2 will fail loud if the import is broken).
    assert subject is None or hasattr(subject, "__name__")
