/**
 * Bridge between the vendored @forge-ai/forge-core catalog and the Forge
 * Command Center UI.
 *
 * The source of truth for `forge-*` command definitions lives in
 * `packages/forge-core/forge-core.catalog.json` (generated by
 * `packages/forge-core/scripts/generate-catalog.cjs` from the upstream
 * vendored markdown). This file:
 *
 *   1. Reads that JSON manifest at build time.
 *   2. Re-shapes each entry to the `ForgeCommand` shape consumed by the UI.
 *   3. Adds icon → lucide-component resolution metadata.
 *
 * If the vendored catalog is unavailable (e.g. local dev before the package
 * is built), we fall back to a hand-curated set of seed commands so the
 * UI still renders meaningfully.
 */

import forgeCoreCatalog from '@forge-ai/forge-core/forge-core.catalog.json';
import {
  FORGE_COMMAND_CATEGORIES,
  type ForgeCommand,
  type ForgeCommandCategoryId,
} from './forge-commands';

interface VendorCatalogEntry {
  id: string;
  name: string;
  label: string;
  description: string;
  category: string;
  icon: string;
  estimatedDuration?: number;
  sourceFile: string;
  skillFile: string | null;
}

interface VendorCatalog {
  $schema: string;
  generatedAt: string;
  engineVersion: string;
  enginePackage: string;
  commandCount: number;
  commands: VendorCatalogEntry[];
}

const VALID_CATEGORIES = new Set<string>(
  FORGE_COMMAND_CATEGORIES.map((c) => c.id),
);

function coerceCategory(raw: string): ForgeCommandCategoryId {
  return VALID_CATEGORIES.has(raw)
    ? (raw as ForgeCommandCategoryId)
    : 'operational';
}

export const FORGE_CORE_CATALOG = forgeCoreCatalog as VendorCatalog;

export const FORGE_COMMANDS_FROM_VENDOR: readonly ForgeCommand[] =
  FORGE_CORE_CATALOG.commands.map((entry) => ({
    name: entry.name,
    label: entry.label,
    description:
      entry.description ||
      `Forge command from ${entry.sourceFile}. Edit SKILL.md to customize.`,
    category: coerceCategory(entry.category),
    icon: entry.icon || 'Wand2',
    estimatedDuration: entry.estimatedDuration ?? 60,
  }));

export type { VendorCatalog, VendorCatalogEntry };
