#!/usr/bin/env python3
"""Regenerate docs/reference/api-catalog.md from backend/app/api/v1/**.

Ponytail: stdlib ast only — no libcst/parso/rope. FastAPI routers all use
@router.<method>("<path>", ...) which ast.parse + ast.walk handles in one
pass.

Usage:
    ./scripts/gen-api-catalog.py            # rewrite docs/reference/api-catalog.md
    ./scripts/gen-api-catalog.py --check    # exit 1 if drift
    ./scripts/gen-api-catalog.py --dry-run  # print to stdout

Output:
    docs/reference/api-catalog.md
"""
from __future__ import annotations

import argparse
import ast
import datetime as dt
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
V1 = REPO / "backend" / "app" / "api" / "v1"
OUT = REPO / "docs" / "reference" / "api-catalog.md"
PREFIX = "/api/v1"

SKIP_NAMES = {"__init__.py", "router.py", "_package_wiring.py"}
HTTP_METHODS = {"get", "post", "put", "patch", "delete"}


def _path_arg(call: ast.Call) -> str | None:
    if not call.args:
        return None
    first = call.args[0]
    if isinstance(first, ast.Constant) and isinstance(first.value, str):
        return first.value
    return None


def _is_http_decorator(dec: ast.expr) -> str | None:
    call = dec if isinstance(dec, ast.Call) else None
    if call is None:
        return None
    func = call.func
    if isinstance(func, ast.Attribute) and func.attr in HTTP_METHODS:
        return func.attr
    return None


def collect_routes() -> list[dict]:
    routes: list[dict] = []
    for py in sorted(V1.rglob("*.py")):
        rel = py.relative_to(V1)
        if rel.name in SKIP_NAMES:
            continue
        try:
            tree = ast.parse(py.read_text(encoding="utf-8"))
        except SyntaxError as e:
            print(f"warn: cannot parse {py}: {e}", file=sys.stderr)
            continue
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for dec in node.decorator_list:
                method = _is_http_decorator(dec)
                if method is None:
                    continue
                path = _path_arg(dec)
                if path is None:
                    continue
                doc = ast.get_docstring(node) or ""
                summary = doc.splitlines()[0].strip() if doc else ""
                routes.append({
                    "file": str(rel),
                    "method": method.upper(),
                    "path": path,
                    "summary": summary,
                })
    routes.sort(key=lambda r: (r["file"], r["path"]))
    return routes


def _full_path(path: str) -> str:
    if path.startswith("/"):
        return f"{PREFIX}{path}"
    return f"{PREFIX}/{path}"


def render(routes: list[dict], today: str) -> str:
    by_file: dict[str, list[dict]] = {}
    for r in routes:
        by_file.setdefault(r["file"], []).append(r)
    lines = [
        "# Reference: API Catalog (All Backend Routes)",
        "",
        "<!-- AUTO-GENERATED. DO NOT EDIT. Regenerate via ./scripts/gen-api-catalog.py -->",
        "",
        "> **Status:** ✅ Auto-generated",
        "> **Doc owner:** Platform team",
        "> **Source of truth:** `backend/app/api/v1/`",
        f"> **Last regenerated:** {today}",
        f"> **Total routes:** {len(routes)}",
        f"> **Total router files:** {len(by_file)}",
        "",
        "---",
        "",
        "## Purpose",
        "",
        "Canonical inventory of every backend REST route. For per-feature route",
        "semantics, see `docs/features/<feature>.md`.",
        "",
        "## Conventions",
        "",
        "- All routes under `/api/v1/`",
        "- All mutating routes have `@audit(action=..., target_type=...)`",
        "- All mutations have RBAC permission guards",
        "- All POST/PUT/PATCH send `Idempotency-Key: <uuid-v4>`",
        "- All list endpoints return `Page[T]`",
        "",
        "## Routes by file",
        "",
    ]
    for f in sorted(by_file):
        items = by_file[f]
        lines.append(f"### `{f}` — {len(items)} routes")
        lines.append("")
        lines.append("| Method | Path | Description |")
        lines.append("|---|---|---|")
        for r in items:
            full = _full_path(r["path"])
            desc = r["summary"] or ""
            lines.append(f"| `{r['method']}` | `{full}` | {desc} |")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"_Generated by `scripts/gen-api-catalog.py` on {today}._")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    routes = collect_routes()
    today = dt.date.today().isoformat()
    body = render(routes, today)

    if args.dry_run:
        sys.stdout.write(body)
        return 0

    if args.check:
        if not OUT.exists():
            print(f"::error::{OUT} missing — run ./scripts/gen-api-catalog.py", file=sys.stderr)
            return 1
        existing = OUT.read_text(encoding="utf-8")
        if existing != body:
            print(f"::error::{OUT} is stale. Run ./scripts/gen-api-catalog.py", file=sys.stderr)
            return 1
        return 0

    OUT.write_text(body, encoding="utf-8")
    by_file = {r["file"] for r in routes}
    print(f"wrote {OUT} ({len(routes)} routes across {len(by_file)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
