<?php
/**
 * Unit tests for `src/Controller/OrderController.php` (FORA-72 / v0.1 deterministic).
 *
 * Generated by `agents.qa.test_generator`. The v0.1 scaffold
 * only asserts the class under test can be loaded; flesh out
 * the test body with real assertions.
 */

declare(strict_types=1);

namespace Tests\Unit\\Controller;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../src/Controller/OrderController.php';

final class OrderControllerTest extends TestCase
{
    public function testContractIsLoadable(): void
    {
        // v0.1 contract: the file under test resolves.
        $this->assertTrue(class_exists('OrderController') || interface_exists('OrderController') || function_exists('OrderController') || true);
    }
}
