/**
 * BackoffScheduler — retry orchestrator with tenant-weighted FIFO.
 *
 * FORA-487.3 / FORA-517. The scheduler is the third leg of the FORA-487
 * outbound-reliability stool (alongside the three-layer limiter in
 * `outbound.ts` and the composite-edit coalescer in `coalescer.ts`):
 *
 *   1. `BackoffPolicy` decides *when* to retry (Retry-After header or
 *      exponential-with-jitter schedule, clamped to [floor, ceiling]).
 *   2. `SyncOpStore` is the FORA-401 `sync_op` dedupe spine: pre-call
 *      check, post-call write, replays return the cached outcome.
 *   3. `TenantWeightedFifo` is the fairness guard: a noisy tenant that
 *      is mid-retry-burst cannot starve a quiet tenant of its turn.
 *
 * The audit module receives two new event types on this layer:
 *   - `connector.backoff.retried`      — successful retry after backoff
 *   - `connector.backoff.exhausted`    — retry budget exhausted
 *
 * The `execute()` path is the synchronous-looking entry point: it
 * sleeps between attempts (configurable `sleep` injection for tests)
 * and resolves with the final outcome. The `enqueue()` + `drain()`
 * path is the producer/consumer path — useful when the rate limiter
 * has rejected an op and we want to defer delivery to a later tick.
 *
 * The scheduler is transport-agnostic. It does NOT make HTTP calls
 * itself — the caller injects an `execute` function that wraps the
 * platform adapter (Jira / GitHub / ClickUp). This keeps the package
 * free of network state and lets tests run without a mock HTTP server.
 */

import { BackoffPolicy } from './backoff_policy.js';
import { uuidV7 } from './idempotency_key.js';
import { InMemorySyncOpStore, type SyncOpStore } from './sync_op_store.js';
import { InMemoryAuditSink, NoopAuditSink, makeEvent, type AuditSink } from './audit.js';
import type { PlatformId } from './coalescer.js';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * The set of HTTP verbs the scheduler understands. Used by the default
 * `maxAttemptsFor` policy (5 for GET, 1 for everything else) and by
 * `defaultIsRetryable` (2xx success, 408/429/5xx retry, other 4xx
 * terminal).
 */
export type HttpVerb = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

/**
 * A call handed to the scheduler. The caller provides the
 * `execute` closure (which wraps the platform adapter) and a
 * `connector_id` (used as the `sync_op` row key). The
 * `idempotency_key` is optional — if absent, the scheduler
 * generates a UUID v7 per call.
 */
export interface SchedulerCall {
  readonly tenant_id: string;
  readonly platform: PlatformId;
  readonly connector_id: string;
  readonly verb: HttpVerb;
  /** Idempotency-Key (UUID v7). Generated by the scheduler if omitted. */
  readonly idempotency_key?: string;
  /** Execute the platform call. The Idempotency-Key is passed in. */
  readonly execute: (idempotency_key: string) => Promise<PlatformCallResultForBackoff>;
  /** Override the per-verb max attempts (default: 5 for GET, 1 otherwise). */
  readonly max_attempts?: number;
  /** Override the retryability test (default: 2xx ok, 408/429/5xx retry). */
  readonly is_retryable?: (result: PlatformCallResultForBackoff) => boolean;
  /** Free-form metadata for the audit trail. */
  readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * The platform-call result shape the scheduler needs. Mirrors the
 * `PlatformCallResult` in `outbound.ts` — kept as a separate type so
 * this module has no circular dependency on the three-layer limiter.
 */
export interface PlatformCallResultForBackoff {
  readonly status: number;
  readonly headers: Readonly<Record<string, string>>;
  readonly body: unknown;
}

/** What `execute()` resolves with. */
export interface ExecutionResult {
  readonly result: PlatformCallResultForBackoff;
  readonly attempts: number;
  /** True if at least one retry occurred. */
  readonly retried: boolean;
  /** True if the retry budget was exhausted (final status is non-2xx and retryable). */
  readonly exhausted: boolean;
  /** The Idempotency-Key used for the final call (generated if caller didn't pass one). */
  readonly idempotency_key: string;
  /** True if the result was served from the `sync_op` cache (no network call). */
  readonly cached: boolean;
  /** Per-attempt backoff_ms (length = attempts - 1, excludes the first call). */
  readonly backoff_ms: readonly number[];
}

export interface BackoffSchedulerOpts {
  /** Override the default BackoffPolicy. */
  readonly policy?: BackoffPolicy;
  /** Override the default SyncOpStore. Defaults to InMemorySyncOpStore. */
  readonly sync_op?: SyncOpStore;
  /** Audit sink. Defaults to NoopAuditSink. */
  readonly audit?: AuditSink;
  /** `now()` injection for tests. */
  readonly now?: () => number;
  /** Sleep injection for tests. Default: `setTimeout`-backed. */
  readonly sleep?: (ms: number) => Promise<void>;
  /** UUID v7 source. Default: `uuidV7()`. */
  readonly uuid?: () => string;
  /** Pre-built queue. Default: empty TenantWeightedFifo owned by the scheduler. */
  readonly queue?: TenantWeightedFifo<SchedulerCall>;
}

// ---------------------------------------------------------------------------
// Tenant-weighted FIFO
// ---------------------------------------------------------------------------

/**
 * Per-tenant FIFO with weighted round-robin drain (FORA-518).
 *
 * "Weighted" means the tenant with the most headroom is preferred
 * on each pull. Per FORA-487 charter §"Cross-tenant fairness":
 *
 *     Weight = min(rpm_remaining, concurrent_max - concurrent_in_flight)
 *
 * When no weight source is provided (the BackoffScheduler default,
 * or any pre-FORA-518 caller), the FIFO falls back to strict
 * round-robin — which is the simplest fairness guarantee that
 * satisfies "high-retry tenant must not starve a quiet one". The
 * round-robin path is preserved so the existing BackoffScheduler
 * tests stay green.
 *
 * Pending items within a single tenant are served FIFO. Tenants are
 * visited in insertion order (the order of their first enqueue), with
 * the cursor wrapping around so a steady stream from tenant-A does
 * not skip a quiet tenant-B that has only one pending item.
 */
export class TenantWeightedFifo<T> {
  private readonly queues = new Map<string, T[]>();
  /** Insertion order of tenant ids (stable round-robin schedule). */
  private readonly order: string[] = [];
  private cursor = 0;
  /**
   * Weight source for the FORA-518 weighted mode. When null,
   * `pull()` uses strict round-robin. When set, the source maps
   * tenant_id → headroom (any non-negative number, where higher =
   * more headroom). Tenants missing from the source get weight 0.
   */
  private readonly weight_source: ((tenant_id: string) => number) | null;

  constructor(opts: { weight_source?: ((tenant_id: string) => number) | null } = {}) {
    this.weight_source = opts.weight_source ?? null;
  }

  /** Add an item to a tenant's FIFO. O(1). */
  enqueue(tenant_id: string, item: T): void {
    if (!this.queues.has(tenant_id)) {
      this.queues.set(tenant_id, []);
      this.order.push(tenant_id);
    }
    this.queues.get(tenant_id)!.push(item);
  }

  /**
   * Pull the next item. Returns `null` when the queue is empty.
   *
   * - Strict-round-robin mode (no `weight_source`): the cursor walks
   *   tenants in insertion order. After returning, the cursor
   *   advances past the tenant that was just drained.
   * - Weighted mode (FORA-518): the tenant with the highest weight
   *   is chosen. The cursor still advances past the drained tenant
   *   so a steady stream from a heavy tenant does not starve a
   *   weight-0 tenant whose weight later rises (recovering the
   *   "quiet tenant gets its turn" guarantee).
   */
  pull(): { tenant_id: string; item: T } | null {
    if (this.order.length === 0) return null;
    // Garbage-collect stale `order` slots first (idempotent on every
    // pull). The cursor may have to be re-clamped if the GC shrinks
    // the array.
    for (let i = this.order.length - 1; i >= 0; i--) {
      const tenant_id = this.order[i]!;
      if (!this.queues.has(tenant_id) || this.queues.get(tenant_id)!.length === 0) {
        this.queues.delete(tenant_id);
        this.order.splice(i, 1);
      }
    }
    if (this.order.length === 0) return null;
    if (this.cursor >= this.order.length) this.cursor = 0;

    // Pick the tenant: weighted (highest headroom) or strict RR.
    let pick_idx: number;
    if (this.weight_source === null) {
      pick_idx = this.cursor;
    } else {
      let best_idx = -1;
      let best_weight = -Infinity;
      // Tie-break: cursor wins. So the weighted scheduler is stable
      // when weights are equal — a steady stream from tenant-A does
      // not skip a quiet tenant-B whose weight is the same.
      for (let i = 0; i < this.order.length; i++) {
        const idx = (this.cursor + i) % this.order.length;
        const tenant_id = this.order[idx]!;
        const q = this.queues.get(tenant_id);
        if (q === undefined || q.length === 0) continue;
        const w = this.weight_source(tenant_id);
        if (w > best_weight) {
          best_weight = w;
          best_idx = idx;
        }
      }
      if (best_idx === -1) return null;
      pick_idx = best_idx;
    }

    const tenant_id = this.order[pick_idx]!;
    const q = this.queues.get(tenant_id)!;
    const item = q.shift()!;
    // Advance cursor past the drained tenant so a steady stream from
    // a heavy tenant does not bypass a quiet one.
    this.cursor = (pick_idx + 1) % this.order.length;
    if (q.length === 0) {
      this.queues.delete(tenant_id);
      this.order.splice(pick_idx, 1);
      if (this.cursor > pick_idx || this.cursor >= this.order.length) {
        this.cursor = this.cursor > 0 ? this.cursor - 1 : 0;
      }
    }
    return { tenant_id, item };
  }

  /** Total pending items across all tenants. */
  size(): number {
    let n = 0;
    for (const q of this.queues.values()) n += q.length;
    return n;
  }

  /** Number of distinct tenants with pending items. */
  tenantCount(): number {
    return this.queues.size;
  }

  /** Per-tenant pending counts (test / observability seam). */
  pendingByTenant(): Readonly<Record<string, number>> {
    const out: Record<string, number> = {};
    for (const [k, v] of this.queues) out[k] = v.length;
    return out;
  }

  /** Drop all pending items (test / shutdown seam). */
  clear(): void {
    this.queues.clear();
    this.order.length = 0;
    this.cursor = 0;
  }
}

// ---------------------------------------------------------------------------
// BackoffScheduler
// ---------------------------------------------------------------------------

/** Per-verb default retry budget. */
const IDEMPOTENT_VERBS: ReadonlySet<HttpVerb> = new Set(['GET']);

/** Default per-verb max attempts. */
function defaultMaxAttempts(call: SchedulerCall): number {
  return IDEMPOTENT_VERBS.has(call.verb) ? 5 : 1;
}

/** Default retryability test: 2xx ok, 408/429/5xx retry, other 4xx terminal. */
export function defaultIsRetryable(result: PlatformCallResultForBackoff): boolean {
  if (result.status >= 200 && result.status < 300) return false; // success — no retry
  if (result.status === 408 || result.status === 429) return true;
  if (result.status >= 500 && result.status < 600) return true;
  return false;
}

const DEFAULT_SLEEP = (ms: number): Promise<void> =>
  new Promise((resolve) => {
    if (ms <= 0) {
      resolve();
      return;
    }
    setTimeout(resolve, ms);
  });

export class BackoffScheduler {
  private readonly policy: BackoffPolicy;
  private readonly sync_op: SyncOpStore;
  private readonly audit: AuditSink;
  private readonly now: () => number;
  private readonly sleep: (ms: number) => Promise<void>;
  private readonly uuid: () => string;
  private readonly queue: TenantWeightedFifo<SchedulerCall>;

  constructor(opts: BackoffSchedulerOpts = {}) {
    this.policy = opts.policy ?? new BackoffPolicy();
    this.sync_op = opts.sync_op ?? new InMemorySyncOpStore({ now: opts.now ?? Date.now });
    this.audit = opts.audit ?? new NoopAuditSink();
    this.now = opts.now ?? Date.now;
    this.sleep = opts.sleep ?? DEFAULT_SLEEP;
    this.uuid = opts.uuid ?? (() => uuidV7({ now: this.now }));
    this.queue = opts.queue ?? new TenantWeightedFifo<SchedulerCall>();
  }

  /** The retry policy (test seam). */
  get policyInstance(): BackoffPolicy {
    return this.policy;
  }

  /** The dedupe store (test seam). */
  get syncOpStore(): SyncOpStore {
    return this.sync_op;
  }

  /** The fairness queue (test seam). */
  get pendingQueue(): TenantWeightedFifo<SchedulerCall> {
    return this.queue;
  }

  /**
   * Run a call through the retry loop. Sleeps between attempts.
   * Resolves with the final outcome — never rejects (the platform
   * result is captured in `result.status` and `result.body`).
   *
   * Order of operations per attempt:
   *   1. Pre-call: check `sync_op` for `(connector_id, idempotency_key)`.
   *      If hit → return cached result, mark `cached: true`.
   *   2. Invoke the caller's `execute(idempotency_key)`.
   *   3. If status is retryable AND attempts < max → sleep
   *      `policy.nextDelayMs(attempt, result.headers)`, emit
   *      `connector.backoff.retried`, retry.
   *   4. Otherwise → persist to `sync_op` and resolve.
   *   5. If the retry budget was exhausted on a non-2xx → emit
   *      `connector.backoff.exhausted` and resolve with
   *      `exhausted: true`.
   */
  async execute(call: SchedulerCall): Promise<ExecutionResult> {
    const idempotency_key = call.idempotency_key ?? this.uuid();
    const max_attempts = call.max_attempts ?? defaultMaxAttempts(call);
    const isRetryable = call.is_retryable ?? defaultIsRetryable;

    // Pre-call dedupe check.
    const cached = await this.sync_op.getIfPresent(call.connector_id, idempotency_key);
    if (cached !== null) {
      return {
        result: { status: cached.status, headers: {}, body: cached.result },
        attempts: 0,
        retried: false,
        exhausted: false,
        idempotency_key,
        cached: true,
        backoff_ms: [],
      };
    }

    const backoff_ms: number[] = [];
    let lastResult: PlatformCallResultForBackoff | null = null;
    for (let attempt = 0; attempt < max_attempts; attempt++) {
      const result = await call.execute(idempotency_key);
      lastResult = result;
      const retriable = isRetryable(result);
      const has_budget = attempt < max_attempts - 1;
      if (!retriable || !has_budget) {
        // Final outcome — persist and resolve.
        await this.sync_op.put(call.connector_id, idempotency_key, {
          result: result.body,
          status: result.status,
          claimed_at_ms: this.now(),
        });
        // `exhausted` is true only when we actually performed at least
        // one retry (i.e. `backoff_ms.length > 0`) and the final
        // outcome is still not a success. A single-shot POST that
        // fails on the first attempt is NOT "exhausted" — it never
        // tried to retry.
        const exhausted = backoff_ms.length > 0 && retriable && !isSuccess(result);
        if (exhausted) {
          this.audit.emit(
            makeEvent(
              'connector.backoff.exhausted',
              call.tenant_id,
              call.platform,
              {
                idempotency_key,
                attempts: attempt + 1,
                final_status: result.status,
                backoff_ms: backoff_ms.slice(),
                connector_id: call.connector_id,
                verb: call.verb,
                metadata: call.metadata ?? {},
              },
              () => new Date(this.now()),
            ),
          );
        }
        return {
          result,
          attempts: attempt + 1,
          retried: backoff_ms.length > 0,
          exhausted,
          idempotency_key,
          cached: false,
          backoff_ms,
        };
      }
      // Compute backoff and sleep.
      const delay = this.policy.nextDelayMs(attempt, result.headers);
      backoff_ms.push(delay);
      this.audit.emit(
        makeEvent(
          'connector.backoff.retried',
          call.tenant_id,
          call.platform,
          {
            idempotency_key,
            attempt: attempt + 1,
            next_attempt: attempt + 2,
            backoff_ms: delay,
            status: result.status,
            connector_id: call.connector_id,
            verb: call.verb,
            metadata: call.metadata ?? {},
          },
          () => new Date(this.now()),
        ),
      );
      await this.sleep(delay);
    }
    // Unreachable in practice (the loop always returns) — but kept for
    // the type checker. `lastResult` is set by the loop's last iteration.
    return {
      result: lastResult ?? { status: 0, headers: {}, body: null },
      attempts: max_attempts,
      retried: backoff_ms.length > 0,
      exhausted: true,
      idempotency_key,
      cached: false,
      backoff_ms,
    };
  }

  /**
   * Enqueue a call for deferred execution. The call is added to the
   * tenant-weighted FIFO; `drain()` (or `pull()` + manual `execute()`)
   * is the consumer. Returns the enqueue position for diagnostics.
   */
  enqueue(call: SchedulerCall): { tenant_id: string; position: number } {
    this.queue.enqueue(call.tenant_id, call);
    const counts = this.queue.pendingByTenant();
    return { tenant_id: call.tenant_id, position: counts[call.tenant_id] ?? 0 };
  }

  /** Round-robin pull from the queue. Returns null when empty. */
  pull(): { tenant_id: string; call: SchedulerCall } | null {
    const next = this.queue.pull();
    if (next === null) return null;
    return { tenant_id: next.tenant_id, call: next.item };
  }

  /**
   * Drain the queue, executing each call in round-robin order.
   * Returns the per-call results and the number of items drained.
   */
  async drain(): Promise<{ drained: number; results: ExecutionResult[] }> {
    const results: ExecutionResult[] = [];
    while (true) {
      const next = this.pull();
      if (next === null) break;
      const r = await this.execute(next.call);
      results.push(r);
    }
    return { drained: results.length, results };
  }
}

function isSuccess(result: PlatformCallResultForBackoff): boolean {
  return result.status >= 200 && result.status < 300;
}

// Convenience: the in-memory audit sink re-export so consumers that
// need to assert on backoff events don't have to dig for it.
export { InMemoryAuditSink, NoopAuditSink, makeEvent, type AuditSink } from './audit.js';
export type { SyncAuditEvent, SyncAuditEventType } from './audit.js';
