// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/llm-gateway" | "/admin/llm-gateway/health" | "/admin/llm-gateway/mcp-servers" | "/admin/llm-gateway/tenants" | "/admin/llm-gateway/tenants/[id]" | "/admin/llm-gateway/tenants/[id]/keys" | "/admin/seeds" | "/agent-center" | "/analytics" | "/analytics/usage" | "/analytics/usage/workflow/[run_id]" | "/architecture" | "/audit" | "/connector-center" | "/connector-center/[id]" | "/copilot" | "/dashboard" | "/forge-command-center" | "/forge-terminal" | "/governance-center" | "/governance/compliance" | "/ideation" | "/knowledge-center" | "/organization-knowledge" | "/persona" | "/personas/cto" | "/personas/eng-lead" | "/personas/pm" | "/project-intelligence" | "/project-intelligence/drafts/[id]" | "/project-intelligence/epics/[id]" | "/project-intelligence/stories/[id]" | "/project-onboarding" | "/refactor" | "/refactor/[plan_id]" | "/refactor/new" | "/runs" | "/runs/[id]" | "/validator" | "/validator/[report_id]" | "/validator/live" | "/welcome"
type AppRouteHandlerRoutes = "/api/persona" | "/api/proxy/[...path]" | "/api/runs/[id]/[verb]" | "/healthz"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/llm-gateway": {}
  "/admin/llm-gateway/health": {}
  "/admin/llm-gateway/mcp-servers": {}
  "/admin/llm-gateway/tenants": {}
  "/admin/llm-gateway/tenants/[id]": { "id": string; }
  "/admin/llm-gateway/tenants/[id]/keys": { "id": string; }
  "/admin/seeds": {}
  "/agent-center": {}
  "/analytics": {}
  "/analytics/usage": {}
  "/analytics/usage/workflow/[run_id]": { "run_id": string; }
  "/api/persona": {}
  "/api/proxy/[...path]": { "path": string[]; }
  "/api/runs/[id]/[verb]": { "id": string; "verb": string; }
  "/architecture": {}
  "/audit": {}
  "/connector-center": {}
  "/connector-center/[id]": { "id": string; }
  "/copilot": {}
  "/dashboard": {}
  "/forge-command-center": {}
  "/forge-terminal": {}
  "/governance-center": {}
  "/governance/compliance": {}
  "/healthz": {}
  "/ideation": {}
  "/knowledge-center": {}
  "/organization-knowledge": {}
  "/persona": {}
  "/personas/cto": {}
  "/personas/eng-lead": {}
  "/personas/pm": {}
  "/project-intelligence": {}
  "/project-intelligence/drafts/[id]": { "id": string; }
  "/project-intelligence/epics/[id]": { "id": string; }
  "/project-intelligence/stories/[id]": { "id": string; }
  "/project-onboarding": {}
  "/refactor": {}
  "/refactor/[plan_id]": { "plan_id": string; }
  "/refactor/new": {}
  "/runs": {}
  "/runs/[id]": { "id": string; }
  "/validator": {}
  "/validator/[report_id]": { "report_id": string; }
  "/validator/live": {}
  "/welcome": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
