/**
 * Stories Center — mock data fixture (Step 21).
 *
 * In-memory fixtures used by the kanban / list / timeline views. The
 * data shape matches `Story` from ./types so the views can be tested
 * deterministically without backend round-trips.
 *
 * All IDs / timestamps are stable so the views can be diffed across
 * renders. Replace with real API once the Stories service lands.
 */

import type {
  Assignee,
  Comment,
  DefinitionOfDone,
  Sprint,
  Story,
  Subtask,
  AcceptanceCriterion,
} from './types';

export const ASSIGNEE_POOL: ReadonlyArray<Assignee> = [
  { id: 'u-arun', name: 'Arun Achalam', initials: 'AA', online: true, color: 'var(--accent-primary)' },
  { id: 'u-mei', name: 'Mei Tanaka', initials: 'MT', online: true, color: 'var(--accent-cyan)' },
  { id: 'u-diego', name: 'Diego Reyes', initials: 'DR', online: false, color: 'var(--accent-emerald)' },
  { id: 'u-priya', name: 'Priya Iyer', initials: 'PI', online: true, color: 'var(--accent-amber)' },
  { id: 'u-noor', name: 'Noor Hassan', initials: 'NH', online: false, color: 'var(--accent-violet)' },
  { id: 'u-bot', name: 'Forge Agent', initials: 'F', online: true, color: 'var(--accent-rose)' },
];

export const SPRINTS: ReadonlyArray<Sprint> = [
  {
    id: 'sp-backlog',
    name: 'Backlog',
    start: '2026-04-01',
    end: '2026-12-31',
    isCurrent: false,
  },
  {
    id: 'sp-25-13',
    name: 'Sprint 25.13',
    start: '2026-06-16',
    end: '2026-06-29',
    isCurrent: true,
    goal: 'Ship the Stories Center + draw the audit timeline in the drawer.',
  },
  {
    id: 'sp-25-14',
    name: 'Sprint 25.14',
    start: '2026-06-30',
    end: '2026-07-13',
    isCurrent: false,
  },
  {
    id: 'sp-25-15',
    name: 'Sprint 25.15',
    start: '2026-07-14',
    end: '2026-07-27',
    isCurrent: false,
  },
];

const DoD: ReadonlyArray<DefinitionOfDone> = [
  { id: 'dod-cr', label: 'Code reviewed', done: true, locked: true },
  { id: 'dod-tp', label: 'Tests pass', done: true, locked: true },
  { id: 'dod-du', label: 'Docs updated', done: false, locked: true },
  { id: 'dod-dd', label: 'Deployed to demo', done: false, locked: true },
];

const subtasks = (...titles: ReadonlyArray<readonly [string, boolean]>): ReadonlyArray<Subtask> =>
  titles.map(([title, done], i) => ({ id: `sub-${i}-${title.slice(0, 4)}`, title, done }));

const acs = (...items: ReadonlyArray<readonly [string, boolean]>): ReadonlyArray<AcceptanceCriterion> =>
  items.map(([text, done], i) => ({ id: `ac-${i}`, text, done }));

/** Stories fixture — 18 cards spread across columns. Stable IDs. */
export const STORIES: ReadonlyArray<Story> = [
  {
    id: 'st-001',
    identifier: 'S-101',
    title: 'Stories Center kanban with @dnd-kit keyboard support',
    status: 'in_progress',
    priority: 'P0',
    estimate: 'L',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[0]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description:
      'Build a full kanban center under `/stories` with backlog / todo / in-progress / in-review / done columns. Drag-and-drop must be keyboard accessible via @dnd-kit KeyboardSensor.',
    acceptanceCriteria: acs(
      ['Kanban renders 5 columns by default', true],
      ['Pointer drag works', true],
      ['Keyboard drag works (Space pickup, arrows, Space drop, Esc cancel)', true],
      ['WIP limit exceeds triggers rose highlight + soft toast', false],
    ),
    subtasks: subtasks(
      ['Type + mock data', true],
      ['Hero + KPI strip', true],
      ['Filter bar', true],
      ['Kanban board with dnd-kit', true],
      ['List + Timeline views', true],
      ['Drawer with 4 tabs', true],
      ['Empty + loading + error states', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [
      { kind: 'epic', id: 'epic-os', label: 'Forge OS', href: '/project-intelligence?epic=epic-os' },
      { kind: 'adr', id: 'adr-009', label: 'ADR-009 Provider Abstraction Layer' },
      { kind: 'pr', id: 'pr-4471', label: 'feat(stories): kanban + dnd' },
    ],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 4,
    attachmentCount: 1,
    blocked: false,
    createdAt: '2026-06-19T09:14:00Z',
    updatedAt: '2026-06-25T13:42:00Z',
    startedAt: '2026-06-22T09:00:00Z',
    completedAt: null,
    startDate: '2026-06-22',
    endDate: '2026-06-26',
  },
  {
    id: 'st-002',
    identifier: 'S-102',
    title: 'Story detail drawer with Detail / Activity / Attachments / Analytics tabs',
    status: 'in_progress',
    priority: 'P1',
    estimate: 'L',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[1]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description:
      'Right slide-in drawer (720px) opens on card click. Hosts 4 tabs (Detail / Activity / Attachments / Analytics) with sticky footer (status dropdown, assignee combobox, due date, label manager, save indicator).',
    acceptanceCriteria: acs(
      ['Drawer opens at 720px width', true],
      ['Tabs switch with keyboard', true],
      ['Inline-edit title saves on blur', true],
      ['AC % complete is shown', false],
    ),
    subtasks: subtasks(
      ['Header chrome', true],
      ['Detail tab', true],
      ['Activity tab', false],
      ['Attachments tab (mock)', true],
      ['Analytics tab (mock charts)', false],
      ['Sticky footer', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [{ kind: 'epic', id: 'epic-os', label: 'Forge OS' }],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 2,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-19T09:18:00Z',
    updatedAt: '2026-06-25T14:01:00Z',
    startedAt: '2026-06-23T10:00:00Z',
    completedAt: null,
    startDate: '2026-06-23',
    endDate: '2026-06-27',
  },
  {
    id: 'st-003',
    identifier: 'S-103',
    title: 'Filter bar with assignee / priority / label / estimate pills',
    status: 'in_review',
    priority: 'P2',
    estimate: 'M',
    labels: ['feature', 'docs'],
    assignee: ASSIGNEE_POOL[3]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description:
      'Search + 4 filter dimensions. Active filter count badge with "Clear filters" link. Pills show as colored chips with the same dot colors as the cards.',
    acceptanceCriteria: acs(
      ['Search filters across title and identifier', true],
      ['Pills combine with AND semantics', true],
      ['Clear link resets state', true],
    ),
    subtasks: subtasks(
      ['Pill state model', true],
      ['Colored dot mapping', true],
      ['Clear link', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 1,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-20T08:00:00Z',
    updatedAt: '2026-06-25T11:20:00Z',
    startedAt: '2026-06-22T12:00:00Z',
    completedAt: null,
    startDate: '2026-06-22',
    endDate: '2026-06-25',
  },
  {
    id: 'st-004',
    identifier: 'S-104',
    title: 'Bug: drawer traps focus on close button',
    status: 'todo',
    priority: 'P1',
    estimate: 'S',
    labels: ['bug'],
    assignee: ASSIGNEE_POOL[2]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description:
      'When the user closes the drawer via the X button, focus does not return to the originating card — keyboard users lose their place.',
    acceptanceCriteria: acs(
      ['Focus returns to the originating card on close', false],
      ['Works for Esc + click outside + X button', false],
    ),
    subtasks: subtasks(
      ['Audit focus management', false],
      ['Restore focus on close', false],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-24T14:30:00Z',
    updatedAt: '2026-06-24T14:30:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-26',
    endDate: '2026-06-27',
  },
  {
    id: 'st-005',
    identifier: 'S-105',
    title: 'Sprint picker combobox',
    status: 'done',
    priority: 'P2',
    estimate: 'S',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[0]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Sprint picker with current sprint + "Backlog" + future sprints. Shows date range.',
    acceptanceCriteria: acs(
      ['Picker lists backlog + sprints', true],
      ['Date range visible per option', true],
      ['Keyboard navigation works', true],
    ),
    subtasks: subtasks(
      ['Combobox shell', true],
      ['Date range formatter', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-21T10:00:00Z',
    updatedAt: '2026-06-24T16:00:00Z',
    startedAt: '2026-06-22T09:00:00Z',
    completedAt: '2026-06-24T16:00:00Z',
    startDate: '2026-06-22',
    endDate: '2026-06-24',
  },
  {
    id: 'st-006',
    identifier: 'S-106',
    title: 'View toggle — Kanban / List / Timeline',
    status: 'done',
    priority: 'P2',
    estimate: 'M',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[3]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Segmented control in the hero band.',
    acceptanceCriteria: acs(
      ['Three segments', true],
      ['Selected state visible', true],
      ['State persists in URL', false],
    ),
    subtasks: subtasks(
      ['Segmented control', true],
      ['URL sync', false],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-21T10:00:00Z',
    updatedAt: '2026-06-24T17:00:00Z',
    startedAt: '2026-06-22T09:00:00Z',
    completedAt: '2026-06-24T17:00:00Z',
    startDate: '2026-06-22',
    endDate: '2026-06-24',
  },
  {
    id: 'st-007',
    identifier: 'S-107',
    title: 'List view — virtualized table with bulk-select floating action bar',
    status: 'todo',
    priority: 'P1',
    estimate: 'M',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[1]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description:
      'Reuse the Step 14 virtualized pattern. Floating action bar appears when 1+ rows are selected.',
    acceptanceCriteria: acs(
      ['Virtualized render at 200+ rows', false],
      ['Floating bar shows count + Assign / Move / Delete', false],
    ),
    subtasks: subtasks(
      ['Reuse virtualized list', false],
      ['Floating action bar', false],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-27',
    endDate: '2026-06-29',
  },
  {
    id: 'st-008',
    identifier: 'S-108',
    title: 'Timeline view — horizontal swimlanes per assignee',
    status: 'backlog',
    priority: 'P2',
    estimate: 'M',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[1]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-14',
    description: 'Swimlanes per assignee (or epic). Days on X axis, cards positioned by start/end date. Today indicator (cyan vertical line).',
    acceptanceCriteria: acs(
      ['Swimlanes per assignee', false],
      ['Today indicator visible', false],
    ),
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-25T08:00:00Z',
    updatedAt: '2026-06-25T08:00:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-30',
    endDate: '2026-07-04',
  },
  {
    id: 'st-009',
    identifier: 'S-109',
    title: 'KPI strip — 5 tiles',
    status: 'done',
    priority: 'P2',
    estimate: 'S',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[3]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Total in sprint / Backlog / In progress / In review / Done this sprint. 120px tall, gap-4.',
    acceptanceCriteria: acs(
      ['All five tiles render', true],
      ['Sparkline shows on Done tile', true],
    ),
    subtasks: subtasks(
      ['Tile primitives', true],
      ['Sparkline mini', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-21T11:00:00Z',
    updatedAt: '2026-06-23T18:00:00Z',
    startedAt: '2026-06-22T09:00:00Z',
    completedAt: '2026-06-23T18:00:00Z',
    startDate: '2026-06-22',
    endDate: '2026-06-23',
  },
  {
    id: 'st-010',
    identifier: 'S-110',
    title: 'New story dialog',
    status: 'todo',
    priority: 'P1',
    estimate: 'M',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[0]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Title (required), Description (markdown), Epic, Priority, Estimate, Labels, Assignee, Sprint. "Create" + "Create and add another".',
    acceptanceCriteria: acs(
      ['Form validates required title', false],
      ['Create + Create-and-add-another both work', false],
    ),
    subtasks: subtasks(
      ['Form fields', false],
      ['Create handlers', false],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-25T09:30:00Z',
    updatedAt: '2026-06-25T09:30:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-26',
    endDate: '2026-06-28',
  },
  {
    id: 'st-011',
    identifier: 'S-111',
    title: 'Empty states — full and compact variants',
    status: 'done',
    priority: 'P3',
    estimate: 'S',
    labels: ['feature', 'docs'],
    assignee: ASSIGNEE_POOL[0]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Two variants per Step 3: full for no-stories-yet (illustration + description + primary CTA), compact for filtered-to-zero.',
    acceptanceCriteria: acs(
      ['Full empty renders with ListTodo illustration', true],
      ['Compact empty appears on filter-to-zero', true],
    ),
    subtasks: subtasks(
      ['EmptyState wiring', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-21T11:00:00Z',
    updatedAt: '2026-06-23T17:00:00Z',
    startedAt: '2026-06-22T09:00:00Z',
    completedAt: '2026-06-23T17:00:00Z',
    startDate: '2026-06-22',
    endDate: '2026-06-23',
  },
  {
    id: 'st-012',
    identifier: 'S-112',
    title: 'Loading skeleton — 3 placeholder cards per column',
    status: 'todo',
    priority: 'P3',
    estimate: 'S',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[2]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Skeleton kanban with shimmer; no spinner.',
    acceptanceCriteria: acs(
      ['3 placeholders per column', false],
      ['Shimmer animates', false],
    ),
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-25T10:00:00Z',
    updatedAt: '2026-06-25T10:00:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-26',
    endDate: '2026-06-26',
  },
  {
    id: 'st-013',
    identifier: 'S-113',
    title: 'WIP limit exceeded — rose highlight + soft toast',
    status: 'todo',
    priority: 'P2',
    estimate: 'S',
    labels: ['feature'],
    assignee: ASSIGNEE_POOL[1]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'When in-progress > 5, show the WIP count in rose and toast on drop.',
    acceptanceCriteria: acs(
      ['WIP counter turns rose when exceeded', false],
      ['Soft toast on drop, no hard block', false],
    ),
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-25T10:30:00Z',
    updatedAt: '2026-06-25T10:30:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-26',
    endDate: '2026-06-27',
  },
  {
    id: 'st-014',
    identifier: 'S-114',
    title: 'A11y audit — keyboard + screen reader',
    status: 'backlog',
    priority: 'P1',
    estimate: 'M',
    labels: ['docs', 'spike'],
    assignee: ASSIGNEE_POOL[3]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-14',
    description: 'Walk every interaction with keyboard only. Confirm aria-live announces column changes during drag.',
    acceptanceCriteria: [],
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-25T11:00:00Z',
    updatedAt: '2026-06-25T11:00:00Z',
    startedAt: null,
    completedAt: null,
    startDate: '2026-06-30',
    endDate: '2026-07-02',
  },
  {
    id: 'st-015',
    identifier: 'S-115',
    title: 'Backlog: harden audit log retention',
    status: 'backlog',
    priority: 'P3',
    estimate: 'M',
    labels: ['chore'],
    assignee: null,
    epicId: 'epic-os',
    sprintId: 'sp-backlog',
    description: 'Increase retention to 90 days for the audit log.',
    acceptanceCriteria: [],
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-10T08:00:00Z',
    updatedAt: '2026-06-10T08:00:00Z',
    startedAt: null,
    completedAt: null,
  },
  {
    id: 'st-016',
    identifier: 'S-116',
    title: 'Blocked: provider rate-limit spike on Anthropic',
    status: 'blocked',
    priority: 'P0',
    estimate: 'M',
    labels: ['bug'],
    assignee: ASSIGNEE_POOL[5]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Block on Anthropic rate-limit increases. Linked to the Provider Abstraction Layer.',
    acceptanceCriteria: [],
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [
      { kind: 'adr', id: 'adr-009', label: 'ADR-009 Provider Abstraction Layer' },
      { kind: 'run', id: 'run-9981', label: 'Run 9981 — agent stuck on 429' },
    ],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 3,
    attachmentCount: 0,
    blocked: true,
    createdAt: '2026-06-18T14:00:00Z',
    updatedAt: '2026-06-25T08:30:00Z',
    startedAt: null,
    completedAt: null,
  },
  {
    id: 'st-017',
    identifier: 'S-117',
    title: 'Refactor: extract useFilteredStories hook',
    status: 'in_review',
    priority: 'P2',
    estimate: 'S',
    labels: ['chore'],
    assignee: ASSIGNEE_POOL[2]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-13',
    description: 'Move filter state out of page.tsx and into a hook that the kanban / list / timeline views all share.',
    acceptanceCriteria: acs(['Hook lives in lib/stories/useFilteredStories.ts', true]),
    subtasks: subtasks(
      ['Define hook signature', true],
      ['Migrate kanban', true],
    ),
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 1,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-22T11:00:00Z',
    updatedAt: '2026-06-25T12:00:00Z',
    startedAt: '2026-06-23T09:00:00Z',
    completedAt: null,
    startDate: '2026-06-23',
    endDate: '2026-06-25',
  },
  {
    id: 'st-018',
    identifier: 'S-118',
    title: 'Spike: real-time collaboration on story detail',
    status: 'todo',
    priority: 'P3',
    estimate: 'L',
    labels: ['spike'],
    assignee: ASSIGNEE_POOL[4]!,
    epicId: 'epic-os',
    sprintId: 'sp-25-15',
    description: 'Investigate CRDT (Yjs) vs OT for collaborative editing of the story description.',
    acceptanceCriteria: [],
    subtasks: [],
    definitionOfDone: DoD,
    linkedItems: [],
    activity: [],
    comments: [],
    attachments: [],
    commentCount: 0,
    attachmentCount: 0,
    blocked: false,
    createdAt: '2026-06-15T10:00:00Z',
    updatedAt: '2026-06-15T10:00:00Z',
    startedAt: null,
    completedAt: null,
  },
];

export const SAMPLE_COMMENTS: ReadonlyArray<Comment> = [
  {
    id: 'c-1',
    author: ASSIGNEE_POOL[3]!,
    body: 'Pulled `S-101` into In Progress. The @dnd-kit sensors are wired — keyboard pickup with Space works.',
    at: '2026-06-25T10:14:00Z',
  },
  {
    id: 'c-2',
    author: ASSIGNEE_POOL[0]!,
    body: 'Nice. Can we also announce the column change via aria-live so screen readers catch it?',
    at: '2026-06-25T10:21:00Z',
  },
  {
    id: 'c-3',
    author: ASSIGNEE_POOL[3]!,
    body: 'Yep — `aria-live="polite"` on the column body, updated on `onDragEnd`.',
    at: '2026-06-25T10:24:00Z',
  },
];