"""Phase 4 audit event taxonomy — single source of truth.

Auto-generated by ``scripts/generate_phase4_docs.py`` from this file.
Add new event names here; the docs follow.

All events follow ``forge.{domain}.{action}`` per Rule 6.
"""

from __future__ import annotations

from enum import Enum


class Phase4AuditAction(str, Enum):
    # ── F16 Pass-through + Media ─────────────────────────────────────
    PROVIDER_ENABLED = "forge.providers.enabled"
    PROVIDER_DISABLED = "forge.providers.disabled"
    PROVIDER_ACCESSED = "forge.providers.accessed"
    MEDIA_AUDIO_GENERATED = "forge.media.audio_generated"
    MEDIA_TRANSCRIBED = "forge.media.audio_transcribed"
    MEDIA_IMAGE_GENERATED = "forge.media.image_generated"
    MEDIA_IMAGE_EDITED = "forge.media.image_edited"
    MEDIA_VIDEO_STARTED = "forge.media.video_started"
    MEDIA_VIDEO_COMPLETED = "forge.media.video_completed"
    MEDIA_MODERATION_RUN = "forge.media.moderation_run"

    # ── F17 Realtime / A2A ────────────────────────────────────────────
    SESSION_STARTED = "forge.sessions.started"
    SESSION_HEARTBEAT = "forge.sessions.heartbeat"
    SESSION_RESUMED = "forge.sessions.resumed"
    SESSION_PAUSED = "forge.sessions.paused"
    SESSION_CANCELLED = "forge.sessions.cancelled"
    SESSION_EXPIRED = "forge.sessions.expired"
    A2A_HANDSHAKE = "forge.a2a.handshake"
    A2A_DELEGATED = "forge.a2a.delegated"
    A2A_RECEIVED = "forge.a2a.received"

    # ── F18 Identity ──────────────────────────────────────────────────
    SSO_CONFIGURED = "forge.identity.sso_configured"
    SSO_LOGIN = "forge.identity.sso_login"
    SCIM_USER_PROVISIONED = "forge.identity.scim_user_provisioned"
    SCIM_USER_DEPROVISIONED = "forge.identity.scim_user_deprovisioned"
    SCIM_USER_UPDATED = "forge.identity.scim_user_updated"
    OAUTH_CLIENT_REGISTERED = "forge.identity.oauth_client_registered"
    JWT_KEY_ROTATED = "forge.identity.jwt_key_rotated"
    FALLBACK_LOGIN_USED = "forge.identity.fallback_login_used"

    # ── F19 Cache ─────────────────────────────────────────────────────
    CACHE_HIT = "forge.cache.hit"
    CACHE_MISS = "forge.cache.miss"
    CACHE_STORED = "forge.cache.stored"
    CACHE_INVALIDATED = "forge.cache.invalidated"
    CACHE_SETTINGS_CHANGED = "forge.cache.settings_changed"

    # ── F20 Ops / Credentials / FinOps ────────────────────────────────
    CREDENTIAL_ADDED = "forge.credentials.added"
    CREDENTIAL_UPDATED = "forge.credentials.updated"
    CREDENTIAL_DELETED = "forge.credentials.deleted"
    VAULT_CONFIGURED = "forge.credentials.vault_configured"
    CLOUDZERO_INIT = "forge.finops.cloudzero_init"
    CLOUDZERO_DRY_RUN = "forge.finops.cloudzero_dry_run"
    CLOUDZERO_EXPORTED = "forge.finops.cloudzero_exported"
    CLOUDZERO_DELETED = "forge.finops.cloudzero_deleted"
    VANTAGE_INIT = "forge.finops.vantage_init"
    VANTAGE_DRY_RUN = "forge.finops.vantage_dry_run"
    VANTAGE_EXPORTED = "forge.finops.vantage_exported"
    VANTAGE_DELETED = "forge.finops.vantage_deleted"
    SETTINGS_UPDATED = "forge.settings.updated"
    BRANDING_UPDATED = "forge.branding.updated"
    EMAIL_SETTINGS_UPDATED = "forge.email.settings_updated"
    COST_CONFIG_UPDATED = "forge.cost.config_updated"


__all__ = ["Phase4AuditAction"]